### ISSUE TITLE
Use external_uri in proxy: true mode

### ISSUE THREAD

**Issue by bgagnon** [prymitive/karma#1024]
We'd like to configure an `external_uri` that is used for the Karma UI, but only for the clickable hyperlinks. The use case is the following:

* we run Karma with proxy mode to Alertmanager
* we create a silence from the Karma UI
* Karma shows a hyperlink to the silence in Alertmanager...
* ...but this is the internal (proxied) URL, not reachable from the browser

So then, we enable `external_uri`, but:
* this makes Karma go through this for _all_ requests
* this URL to Alertmanager depends on our Ingress stack, making Karma more fragile
* it is not compatible for the `proxy: true` mode, and Karma refuses to start

Questions:
* could Karma discover and honor Alertmanager's `--web.external-url` flag?
* could Karma have a dual mode where `external_uri` is considered only for hyperlinks?
* would a new option, maybe `external_link_uri`, be clearer?

Thanks!

**Comment by bgagnon** [comment]
I looked into discoverability on the Alertmanager, and ended up opening this issue: https://github.com/prometheus/alertmanager/issues/2064

**Comment by prymitive** [comment]
RIght, so let's recap, we have those use cases:

1. backend will read all silences
2. UI can write silences (create/edit/expire)
3. UI can display clickable links pointing at the silence in alertmanager web UI

Then we have:
1. backend always uses `alertmanager.uri`
2. UI write:
a. `proxy: false` - use `alertmanager.uri`
b. `proxy: true` - use karma internal API to talk to the backend, then backend talks to `alertmanager.uri`
c. `external_uri` - use that value when set, regardless of proxy setting
3. UI links: not totally sure how this is generated at the moment to be honest

I need to look into this, config file is getting messy and could use some restrcuturing. Proxy/non-proxy mode and `external_uri` adds to the complexity of deciding what to use where and I need to clean this up a little. Maybe a diagram would be useful.
It could potentially be simplified if proxy was always used for silence management, possibly with a new option to turn read-only mode per instance (so editing silences is not allowed).

I'll look into links and try to clean this up. Thanks!

**Comment by prymitive** [comment]
Raised #1026 that refactors how all those settings interact with each other.
Added more docs on that under the [Alertmanagers section](https://github.com/prymitive/karma/blob/166032ddfca34bc7de285b0d5086e0612c9d72a8/docs/CONFIGURATION.md#alertmanagers)

It should solve your problem while retaining of behaviour of the original request for `external_uri` - #899

**Comment by prymitive** [comment]
Are you able to test `lmierzwa/karma:latest` docker image and verify if it now works as you expected?
You should be able to set both proxy mode and external_uri, in that setup silence management requests (create/edit/delete silences via the UI) would use proxy but links should use `external_uri`.

**Comment by bgagnon** [comment]
Wow, that was unbelievably fast! I'll give it a spin and chime back. Thanks again!
