### ISSUE TITLE
allow for other ticket system than jira

### ISSUE THREAD

**Issue by erdeerdeerde** [prymitive/karma#1140]
Hi there,

First of all: thanks for this great project!

I would like to set links to other ticket systems than JIRA. At the moment this doesn't work, because /browse/ is also appended to the URL.
Also, it would be nice if i can extract groups from the regex, ie. a comment like it-1234 transforms to ticket.system.com/ticket/1234

**Comment by prymitive** [comment]
regex would indeed be most flexible, will try to add it for the next release

**Comment by erdeerdeerde** [comment]
wow, fastest reply ever :) thanks!

**Comment by prymitive** [comment]
Raised #1148 that replaces `@silence_jira` with `@silence_ticket`, there are new config options to configure it
