### ISSUE TITLE
Add /health endpoint returning 200 OK

### ISSUE THREAD

**Issue by analytically** [prymitive/karma#1155]
Handy for schedulers like Nomad and K8s to have a /health endpoint indicating service availability.

**Comment by analytically** [comment]
Currently when using / it looks ugly:

![image](https://user-images.githubusercontent.com/254434/68822581-1fd8ca00-0646-11ea-8cda-1e9dc60143c9.png)

**Comment by prymitive** [comment]
Good idea, I've been using `/alerts.json?q=%40limit%3D1` or `/manifest.json`, having a dedicated `/health` would be nice.
 Do you think that a dummy `200 OK` is enough for this?
