### ISSUE TITLE
karma API number of active alerts returns null

### ISSUE THREAD

**Issue by xkilian** [prymitive/karma#1164]
When there are 0 active alerts, the API returns null. It would be more relevant to return 0 instead of null. Null would be expected if for example no Alertmanagers or metrics available.

Thank you for the great work.

**Comment by prymitive** [comment]
Can you share some example? I'm not entirely sure which field you're talking about. Thanks

**Comment by xkilian** [comment]
Thank you for the fix. Look forward to testing it out.
