### ISSUE TITLE
object.equals() expression

### ISSUE THREAD

**Issue by Dipongkar12** [prymitive/karma#1299]
![pblm](https://user-images.githubusercontent.com/53388453/71458708-3db15700-27ce-11ea-9b28-f7432dfb00ca.PNG)

**Comment by Dipongkar12** [comment]
what is the issue??

**Comment by prymitive** [comment]
What issue? If you're trying to report a bug then please explain the problem you're seeing.
What is the screenshot of some Java source code suppose to mean? There's no java code here, looks like you're after some other github project

**Comment by Dipongkar12** [comment]
![Screenshot_2019-12-23-21-19-59-538_com miui bugreport](https://user-images.githubusercontent.com/53388453/71556674-99494200-2a65-11ea-800a-778dbfb96054.png)
****   Here is the  problem

**Comment by prymitive** [comment]
And how is that relevant to this project? karma is not written in java, there's no way it could generate a java backtrace with youtube uri libraries
