### ISSUE TITLE
Add crossorigin="use-credentials" to rel="manifest" link

### ISSUE THREAD

**Issue by andsens** [prymitive/karma#1341]
While setting up Karma I noticed that the `manifest.json` request failed, because it was being redirected to the login site. The app is reverse-proxied with an authentication server in front, so any request without credentials will just receive the login redirect as a response.

The `<link rel="manifest" href="%PUBLIC_URL%/manifest.json" />` line in [`public.html`](https://github.com/prymitive/karma/blob/20312f1706d9045783062c96ab7833ab6605633c/ui/public/index.html#L14) should specify that credentials are to be included. So:
```
<link rel="manifest" href="%PUBLIC_URL%/manifest.json" crossorigin="use-credentials" />
```

Read more here: https://developers.google.com/web/fundamentals/web-app-manifest/#tell_the_browser_about_your_manifest

**Comment by prymitive** [comment]
Will add that via #1343, thanks!
