### ISSUE TITLE
Error logs contain alertmanager credentials

### ISSUE THREAD

**Issue by fbsb** [prymitive/karma#1363]
While in normal log output the credentials are masked they are still visible in the log output when an error happens.

**Comment by prymitive** [comment]
Can you share any details?
Are you compiling from source? Go should mask all credentials in errors it returns - https://go-review.googlesource.com/c/go/+/102855

**Comment by fbsb** [comment]
Hi!

We're using the upstream docker image `lmierzwa/karma`

The error I'm seeing comes from https://github.com/prymitive/karma/blob/7d410c9964856698a76e5bb388a044490d4fdb6f/cmd/karma/main.go#L128

**Comment by prymitive** [comment]
Should be fixed via #1364, thanks!

**Comment by fbsb** [comment]
Thank you for your quick response and the quick fix. I look forward for a new release soon.

**Comment by prymitive** [comment]
I'll tag a new release in a few days, will try to add more test coverage for this first, to avoid future regressions

**Comment by prymitive** [comment]
https://github.com/prymitive/karma/releases/tag/v0.55 is out
