### ISSUE TITLE
Karma ReadOnly

### ISSUE THREAD

**Issue by abzogodwin** [prymitive/karma#1376]
Hello 

I need help.

How to configure karma in access mode ReadOnly ?

**Comment by prymitive** [comment]
You mean this - https://github.com/prymitive/karma/blob/master/README.md#security ?

**Comment by abzogodwin** [comment]
My question is: 
How to configure the file karma.yaml to deploy ReadOnly not Readandwrite?

**Comment by prymitive** [comment]
Did you read what I linked? Is some part of it not clear?

**Comment by prymitive** [comment]
https://github.com/prymitive/karma/releases/tag/v0.55 has some additional features and documentation improvements for this

**Comment by hali22** [comment]
Are u ok
