### ISSUE TITLE
Keyboard/mouse shortcut for collapsing all groups

### ISSUE THREAD

**Issue by bgagnon** [prymitive/karma#1381]
It would be useful to quickly collapse/expand all groups with `Alt`+`Click` on the collapse arrow.  Or perhaps with a keyboard-only shortcut (no clicking). Currently, this requires clicking on every group separately.

**Comment by prymitive** [comment]
This is doable but a bit more complex to implement as it requires some global event dispatch.

**Comment by prymitive** [comment]
Well, I can simply use the good old browser event dispatch for this
