### ISSUE TITLE
including credentials breaks silences (because of cors)

### ISSUE THREAD

**Issue by flat235** [prymitive/karma#1432]
Hi,

this issue has been reported before: https://github.com/prymitive/karma/issues/715 but has since been closed.
However this has nothing to do with the nginx configuration or some special cors-policy, but is actually something enforced/not supported by the browser.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials for reference.
Please make including credentials configurable, otherwise the default case of "no proxy in front of karma or alertmanager" breaks silences.

Greetings, Moritz

**Comment by prymitive** [comment]
I’m not sure if I fully understand the problem here, why do you try to include credentials if your Access-Control-Allow-Origin value prevents it from working? can you simply not include them in karma config?

**Comment by flat235** [comment]
I don't. I have no credentials in my karma config or anywhere else.
However there seems to be some header, that is always included:
https://github.com/prymitive/karma/search?q=credentials&unscoped_q=credentials

alertmanager runs on its own port, as does karma. no (reverse)proxies.
This is the result (in the browser console) of clicking the silence-button:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://censored.hostname.tld:9093/api/v2/silences’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’). [Learn More]

[Learn More] links to the mentioned mozilla-page on cors.
So I propose making the sending of the "include: credentials"-header configurable in the karma config.

**Comment by flat235** [comment]
relevant PR: https://github.com/prymitive/karma/pull/486

**Comment by prymitive** [comment]
Right, will look into adding more control over headers

**Comment by prymitive** [comment]
You can now set it per alertmanager - [docs](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#alertmanagers)

Example:

```YAML
alertmanager:
  servers:
    - name: am
      uri: https://localhost:9093
      cors:
        credentials: omit
```
