### ISSUE TITLE
Feature request: acknowledge tickbox

### ISSUE THREAD

**Issue by nichrome0** [prymitive/karma#1484]
Hi,
Thank you for this beautiful tool. My uni team is using it on a daily basis for few of our little servers we use for projects.
I would like to ask, if it's possible to add some kind of acknowledgment button for each alert, so that other people can clearly see that someone is already looking at the alert and not carry out the same resolution tasks twice? Only to appear within Karma itself per unique alert.
Thanks

**Comment by prymitive** [comment]
Not sure if I fully follow but isn't it basically this feature https://github.com/prymitive/karma/blob/master/README.md#alert-acknowledgement ?

**Comment by nichrome0** [comment]
Hi. You're right! Got to update it on our side. Thank you
