### ISSUE TITLE
NetworkError when creating silences.

### ISSUE THREAD

**Issue by AngelFreak** [prymitive/karma#1537]
Hey thanks for the great project!

When i try to create silences in Firefox 74.0 (64-bit) i get "NetworkError when attempting to fetch resource.".
I expect to see the silence being created. 

In Chrome Version 63.0.3239.108 (Official Build) (64-bit) i get "Failed to fetch"

Can someone please help ?

**Comment by prymitive** [comment]
Browsers typically don’t return much detail in fetch errors.
Developer console in the browser should have more detailed logs of the error.

**Comment by AngelFreak** [comment]
Sure, here i get the following:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://URL/api/v2/silences’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://URL/api/v2/silences. (Reason: CORS request did not succeed).

**Comment by prymitive** [comment]
You need to disable CORS credentials, see
https://github.com/prymitive/karma/blob/v0.56/docs/CONFIGURATION.md#alertmanagers

**Comment by AngelFreak** [comment]
Thanks a lot, that solved the issue
