### ISSUE TITLE
Regex in annotations

### ISSUE THREAD

**Issue by Seitanas** [prymitive/karma#1545]
Hell, i wonder is there any way to use regex in annotations? 
I need to build an url inside annotation from its value.

**Comment by prymitive** [comment]
Do you mean using a regex as a value for an annotation? If so I don’t think alertmanager supports that, but you should be able to generate a concrete value using Go templating in the alert rule

**Comment by Seitanas** [comment]
The problem I'm facing is that there are some annotations sent from prometheus which are then made into URL by the alertmanager template and sent via Slack.
I would like to build those annotations into URL in karma also.

**Comment by prymitive** [comment]
Karma exposes data from alertmanager API, mutating annotations seems like a non-goal. If I read this right you’re having a partial value as the original annotation and rewriting that in slack receiver template. It feels to me like a slightly hackish way of getting those values, no other receiver will get the rewritten value and so you’ll be forced to replicate that templating logic everywhere you touch those annotations.
I believe that the correct way is to generate final values in the alert rule, is that not possible in your case?

**Comment by Seitanas** [comment]
Yeah, that's what we will do.
Thank you for helping.
