### ISSUE TITLE
connect karma to keycloak

### ISSUE THREAD

**Issue by abzogodwin** [prymitive/karma#1571]
Hello 
I need to connect karma to alermanager through keycloak. Does karma have an http proxy that we can use to point to a proxy via gatekeeper?

**Comment by prymitive** [comment]
Go HTTP client support `HTTP_PROXY` env variable so if you need to have a proxy between karma and alertmanager that could be used.
Example: `http_proxy="http://localhost:8081" ./karma ...`
See https://github.com/prymitive/karma/issues/633#issuecomment-580261121
