### ISSUE TITLE
Regression: Silence preview fails with version v0.57+

### ISSUE THREAD

**Issue by dswarbrick** [prymitive/karma#1573]
After upgrading a previously working v0.56 instance to v0.57 / v0.58, it now throws the following error in the browser when previewing a new silence:
![preview-silence](https://user-images.githubusercontent.com/1667905/78124692-530ed080-7410-11ea-9cde-a8bfcf295f53.png)

Rolling back to v0.56 resolves the issue.

**Comment by prymitive** [comment]
Looks like I forgot to update it when adding multi-grid support, will fix soon, thanks

**Comment by prymitive** [comment]
#1574 will fix it, will make a new release later today
