### ISSUE TITLE
"Silence this group" does not always generate a matching silence

### ISSUE THREAD

**Issue by Neki** [prymitive/karma#1601]
First thing, thanks a lot for this project!

I've stumbled upon an UI issue with karma. If there is an alert group where alerts have different label sets, the silence suggested by the "silence this group" feature will not actually match any alert.

---

As an example, consider these two alerts, where:
* the first one has a unique "container" label, absent from the second one
* the second one has a unique "deployment" label, absent from the first one

![image](https://user-images.githubusercontent.com/2143664/78544797-fe49cc00-77fa-11ea-82c9-a575e190f3a2.png)

If I then click on "silence this group", karma generates this silence:
![image](https://user-images.githubusercontent.com/2143664/78544976-4668ee80-77fb-11ea-9bc3-a75fbacbeca1.png)

However, this silence does not match any alert:
* it matches the "deployment" label, so it doesn't match the first alert
* it also matches the "container" label, so it doesn't match the second alert 

So **clicking on "Preview" will result in "no alerts matched".**

---

This proved to be confusing to people not deeply familiar with alertmanager. I don't know what the correct approach would be here.

**Comment by prymitive** [comment]
Good catch, generated silence assumes that all alerts will have same label sets. I forgot that (for example) one can have multiple alert rules with unique queries that generate alerts with the same name, and that can easily lead to alerts with same name but completely different label sets. Matchers generator need to handle that. Thanks!

**Comment by prymitive** [comment]
This should be fixed in latest master. Only labels that are shared between all alerts will be used.
