### ISSUE TITLE
Label based multi-grid manual sorting options 

### ISSUE THREAD

**Issue by xkilian** [prymitive/karma#1636]
Issue: Some labels do not lend themselves to alphabetical sorting.
Ex: Prod, Pre-Prod, Dev, Test. Or PP, PR, DV, TS.
If there could be some way to either do a manual sort or a hybrid manuel + alphabetical for anything not matching the manual items.
This would permit pinning the 1 or two critical items first in the right order, and whatever else comes next would be using the current sorting mechanism.
ps. I Love the idea and implementation of the multi-grid.

**Comment by prymitive** [comment]
You can override label values for sorting via [grid:sorting: customValues:labels](https://github.com/prymitive/karma/blob/v0.60/docs/CONFIGURATION.md#grid), example:

```YAML
grid:
  sorting:
    customValues:
      labels:
        severity:
          critical: 1
          warning: 2
          info: 3
```

This will be used for all sorting operations, including multi-grid.

**Comment by xkilian** [comment]
Ah.. I had not clearly understood the use of the customValues: labels.
Great stuff, as always. Thank you for the answer. 
The linked documentation is very clear in the text. I probably skimmed it looking at the examples and missed it.
