### ISSUE TITLE
Be able to collapse annotation by clicking on name

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#1721]
Hi,
thanks for Karma!

I wish I could click on an annotation's name to collapse/hide it (in addition to the magnifying glass). This would match the behavior when the annotation is hidden, I can click the annotation name to expand it, what do you think?

best,
Filippo

**Comment by prymitive** [comment]
Sure, will fix that via #1726

**Comment by filippog** [comment]
Thank you!
