### ISSUE TITLE
New silence using current filters

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [prymitive/karma#1750]
First, thanks for your great tool!

I have a question / feature request.

My workflow is, if I want to silence alarms, I filter the view to show only the alarms I will be silencing. When creating a new silence from there, I expected the active filters would be used.
But the silence dialog has no filters preselected (see gif). I expected the silence to have 
```
instance:~10.17.+
``` 
pre-set.

I know there is the feature `Silence this group` but its not the same, as it adds ALL labels as filters to the silence, I may want to create a silence spanning multiple alert groups.

The new silence dialog will remember last used settings which is not that helpful either.

![psIsKqwSnH](https://user-images.githubusercontent.com/33002073/82155252-c90db080-9873-11ea-99ba-f2c9f0b35e0a.gif)

Is there a way of doing this that I'm missing?

**Comment by prymitive** [comment]
New silence form doesn't have any default set of filters, but it does remember last entered values. It does seem like a good idea to default to current global set of filters, will try to add that. Thanks!

**Comment by prymitive** [comment]
WIll add this via #1752
Note that this only work with label filers and `=`, everything else will be ignored.
`@receiver` and other pseudo filters won't work as there's no way to reflect that on a silence, same goes for `foo!=bar`.

**Comment by prymitive** [comment]
Regex filters should also be added, will fix that

**Comment by Mario-Hofstaetter** [comment]
This has to be the single fastest response time to a feature request I've ever seen, unbelievable.

**Comment by Mario-Hofstaetter** [comment]
Are all fixes merged and live on https://karma-demo.herokuapp.com ?
Because it is not working correctly yet there in `Version: v0.61-5-g80160ba` 

It works the first time, the second time you open the silence dialog it has remembered the settings from before and does not use the current active filters:

![veqTZFynwJ](https://user-images.githubusercontent.com/33002073/82217296-8652e380-991a-11ea-9e6e-6fee0eaaf956.gif)

**Comment by prymitive** [comment]
Current filters are used as `default` silence matchers only if there's nothing set on the form, old matchers are still preserved, that behaviour didn't change.
Once you open the form it gets populated, on second open there are matchers set so it doesn't re-populate.

**Comment by prymitive** [comment]
Will keep it open to add some future improvements

**Comment by Mario-Hofstaetter** [comment]
Thank you, I was thinking about this today. While I am not a fan of the "remember last filters" function, I understand that breaking changes are not to be taken lightly.

Maybe a new button in the new silence dialog _somewhere_ to "import/use" the filters currently on the dashboard?

![grafik](https://user-images.githubusercontent.com/33002073/82261964-55959d00-9960-11ea-8c63-cba1ca89e763.png)

There is already a dropdown with filter history
![grafik](https://user-images.githubusercontent.com/33002073/82262046-7e1d9700-9960-11ea-975b-26b94bb8cadb.png)

so maybe incorporate these somehow in the silence dialog?
The first option could be `Current`

![grafik](https://user-images.githubusercontent.com/33002073/82262314-f6845800-9960-11ea-95ec-e01c7b324012.png)

Sorry for this terrible mockups.

**Comment by prymitive** [comment]
Pushed a change that's now visible on https://karma-demo.herokuapp.com/
Silence matchers will get filled from filers every time you open silence modal.
