### ISSUE TITLE
AlertMenu "Alert source links" dropdown hidden by multi-grid when clicked

### ISSUE THREAD

**Issue by koppchen** [prymitive/karma#1754]
Looks like a small bug was introduced in v0.61 that makes it difficult to silence an alert if the AlertMenu "Alert source links" dropdown box hangs over a multi-grid group.  When the menu overlaps a multi-grid group, clicking on the menu makes it go behind the multi-grid, which hides the "Silence this alert" option from the user.

Example:

Initial view showing 2 muli-grid groupings (for severity:info & severity:warn)
![karma-alertmenu-issue-1](https://user-images.githubusercontent.com/8094490/82162409-299bee00-9872-11ea-82e8-4e8ec4e5bbe4.png)

Display AlertMenu "Alert source links" dropdown
![karma-alertmenu-issue-2](https://user-images.githubusercontent.com/8094490/82162410-2bfe4800-9872-11ea-9861-f87a9d9090e6.png)

Clicking on "Silence this alert" (or anywhere in the AlertMenu box) hides the dropdown behind the lower multi-grid group.
![karma-alertmenu-issue-3](https://user-images.githubusercontent.com/8094490/82162412-2e60a200-9872-11ea-9854-86f3f7cea1f3.png)

This works fine if the AlertMenu doesn't overlap a multi-grid group.

Thanks!!!

**Comment by prymitive** [comment]
Should be fixed via #1756. Thanks!

**Comment by koppchen** [comment]
Tested and confirmed, that fixed the issue!  Thank you!
