### ISSUE TITLE
Favicon counter doesn't show until amount of alerts changed.

### ISSUE THREAD

**Issue by vosdev** [prymitive/karma#1761]
using docker v0.61. 

Favicon shows only the recycle logo. Counter doesn't show until there is a change in number of firing alerts.

![image](https://user-images.githubusercontent.com/45820840/82314184-b4dbc780-99c9-11ea-8d3a-5ad50b7cd4f5.png)

Counter is gone after a refresh.

![image](https://user-images.githubusercontent.com/45820840/82314241-c7560100-99c9-11ea-8f11-e853d6b476d9.png)

And after I resolve an alert:

![image](https://user-images.githubusercontent.com/45820840/82314502-359ac380-99ca-11ea-8685-ec4561003347.png)

Tested in Firefox and chromium :)

**Comment by prymitive** [comment]
Should be fixed via #1765, thanks!

**Comment by vosdev** [comment]
Much appreciated 👍

**Comment by vosdev** [comment]
Can you open it again? It's once again broken until a change in firing alerts occurs. :-)

**Comment by prymitive** [comment]
Merged #2148, should help with this, please verify.

Note: I hope you're not relying on favicon badge when karma is a background tab, browsers will suspends updates after some time when you switch to a different tab.

**Comment by vosdev** [comment]
> I hope you're not relying on favicon badge when karma is a background tab, browsers will suspends updates after some time when you switch to a different tab.

Darn I didn't know this :(

> Merged #2148, should help with this, please verify.

Can verify it works 👍  Thank you!
