### ISSUE TITLE
Possible goroutine / memory leak in v0.62

### ISSUE THREAD

**Issue by dswarbrick** [prymitive/karma#1762]
After running for about 19 hours, our karma instance just crashed:
```
May 19 13:42:59 fra-grafana1 karma[26854]: fatal error: runtime: out of memory
May 19 13:42:59 fra-grafana1 karma[26854]: runtime stack:rror: runtime: out of memory
...
May 19 13:43:02 fra-grafana1 karma[26854]: goroutine 141813 [chan receive]:
May 19 13:43:02 fra-grafana1 karma[26854]: github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder(0xc006c37dd0, 0xc0376288a0)
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/decoder.go:457 +0x25f
May 19 13:43:02 fra-grafana1 karma[26854]: created by github.com/klauspost/compress/zstd.(*Decoder).Reset
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/decoder.go:161 +0x3a1
May 19 13:43:02 fra-grafana1 karma[26854]: goroutine 141797 [chan receive]:
May 19 13:43:02 fra-grafana1 karma[26854]: github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc01a28f440)
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/blockdec.go:207 +0x149
May 19 13:43:02 fra-grafana1 karma[26854]: created by github.com/klauspost/compress/zstd.newBlockDec
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/blockdec.go:114 +0x15f
May 19 13:43:02 fra-grafana1 karma[26854]: goroutine 141798 [chan receive]:
May 19 13:43:02 fra-grafana1 karma[26854]: github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder(0xc009a84120, 0xc037640cc0)
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/decoder.go:457 +0x25f
May 19 13:43:02 fra-grafana1 karma[26854]: created by github.com/klauspost/compress/zstd.(*Decoder).Reset
May 19 13:43:02 fra-grafana1 karma[26854]: #011/home/travis/gopath/pkg/mod/github.com/klauspost/compress@v1.10.5/zstd/decoder.go:161 +0x3a1
May 19 13:43:02 fra-grafana1 systemd[1]: karma.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 19 13:43:02 fra-grafana1 systemd[1]: karma.service: Failed with result 'exit-code'.
```
Judging by the very high number of similar-looking goroutines in the backtrace, I suspect a goroutine leak, which is slowly eating memory also.

I suspect the bug actually arrived in v0.61, but we did not run that version. Last known good version is v0.60.

**Comment by prymitive** [comment]
AFAIR zstd compression was the only backend change, so it's likely https://github.com/prymitive/karma/commit/ee07b80d4b9118434463c86434d95320d92bcc79#r39283627 you noted

**Comment by prymitive** [comment]
Was able to reproduce, it's just a missing close as suggsted, #1764 should fix it. Thanks!

**Comment by dswarbrick** [comment]
The goroutine leak is definitely resolved in 0.63, but I still suspect a slow memory leak. I have configured a Prometheus scrape of our karma instance, which I previously did not have. Overall, I've noticed the used memory of the _host_ slowly increasing, so I will keep an eye on the specific memory usage of karma (`go_memstats_alloc_bytes`).

I have downgraded to 0.60 again to build up some baseline metrics first, and the immediate observation is that 0.60 uses dramatically less memory - ~15 MB, vs ~50 MB for 0.61 or later. Whilst this may not be a concern for most people, that is a huge increase, and may be of concern for low-resource kiosk instances, RPi etc.

**Comment by prymitive** [comment]
I’ll try to run some stress tests and add some leak detection to unit tests if possible

**Comment by dswarbrick** [comment]
Ok, so I don't think it's leaking, but the memory footprint is percentage-wise dramatically higher than before. Below is a 12 hour period comparing v0.60 to v0.63, which was installed shortly before 13:30, designated by the annotation on the graph.
![Screenshot_2020-05-21 Karma - Grafana](https://user-images.githubusercontent.com/1667905/82581705-421d4880-9b91-11ea-8636-ef7091c061cf.png)
The occasional short-lived spikes are somewhat curious also.

**Comment by prymitive** [comment]
It seems to be zstd compression of internal cache as it requires a lot more allocations:

```
BenchmarkCompressZSTD-4   	     111	  11789400 ns/op	35040815 B/op	     202 allocs/op
BenchmarkCompressGZIP-4   	     122	   9515157 ns/op	 5392934 B/op	     113 allocs/op
```

I could reduce that by re-using encoder/decoder as suggested in the docs, allocations go down:

```
BenchmarkCompressZSTD-4   	     196	   5731845 ns/op	 4090950 B/op	       2 allocs/op
BenchmarkCompressGZIP-4   	     135	   8685866 ns/op	 5391322 B/op	     113 allocs/op
```

But the downside is that shared encoder/decoder will require extra memory, in a simple test I see it using ~32MB of memory all the time, which might negete savings from compression.
Might just switch back to gzip, it's slower and results in smaller compression, but it doesn't cost too much extra memory.

**Comment by dswarbrick** [comment]
Is the cached data so large that it warrants compressing? I could perhaps see an advantage in compressing it with gzip, _if_ it meant that it could be directly streamed to clients, without karma having to decompress it first (only for nginx / whatever to re-compress the JSON response).

Otherwise unless the data is quite large, it's probably not worth the extra CPU / memory usage to store it compressed.

**Comment by prymitive** [comment]
Size depends on the environment, it definetely helps with lots of users and alerts.
20+MB JSON blobs compress to  <1MB and cached responses are <1ms instead of ~300-500ms.
When data is tiny compression is cheap.

**Comment by dswarbrick** [comment]
When data is tiny, compression is probably not justified. And if implementing compression results in a 40MB increase in RAM usage, that sounds like a net loss.

I imagine that a lot of people would be running Karma behind a reverse proxy such as Nginx or Apache, which can easily be configured to gzip JSON responses from Karma.
