### ISSUE TITLE
Getting ERRO[0000] [default] can't find status mapper for Alertmanager 0.16.0

### ISSUE THREAD

**Issue by Yagyansh** [prymitive/karma#1763]
While running Karma, I am getting the above mentioned error. Not able to find anything about this. Any idea what this is about?

**Comment by prymitive** [comment]
You need to upgrade alertmanager.
It's documented on top of https://github.com/prymitive/karma/blob/master/README.md

`Starting with karma v0.56 only Alertmanager V2 API is supported, which requires Alertmanager >=0.17.0.`

**Comment by Yagyansh** [comment]
But I have downloaded Karma v0.55.

**Comment by prymitive** [comment]
0.16.0 doesn't have required API, see [v0.55 README](https://github.com/prymitive/karma/blob/v0.55/README.md)

```
Alertmanager 0.16.x is NOT supported by karma due to changes in the API, see this issue for details. A new API endpoint was added for 0.17.0 and alertmanager >=0.17.0 is supported.
```

**Comment by Yagyansh** [comment]
Okay, thanks. So, does any version of Karma support Alertmanager 0.16.x?

**Comment by prymitive** [comment]
No, 0.16 dropped the v1 API karma uses, v2 API for that was only added in 0.17.x
