### ISSUE TITLE
Direct link to the "create silence" modal with preset filters?

### ISSUE THREAD

**Issue by Neki** [prymitive/karma#1820]
We've adopted Karma as our main way to silence alerts. There doesn't seem to be a way to add a link in an alertmanager notification to the modal allowing to create a matching silence.

We can link directly to karma with the correct filters, but silencing the alert group then requires two extra clicks (or maybe one now that https://github.com/prymitive/karma/pull/1752 is merged).

I'd like to encourage my team to silence alerts more often, so reducing the friction here would help.

**Comment by prymitive** [comment]
Need to tweak the UI for this but otherwise it’s done.
Right now there’s a copy button on the form that doesn’t look great

**Comment by Neki** [comment]
Wow, that was quick :) Awesome, thanks a lot! If I understand the diff correctly, I'll need to write a small utility to generate the `m` parameter in alertmanager templates the same way Karma does, but that should be doable.
