### ISSUE TITLE
Displayed alerts not refreshing when a filter is edited

### ISSUE THREAD

**Issue by koppchen** [prymitive/karma#1869]
When manually editing a filter in the top search bar, the alerts displayed aren't updated until the refresh triggered by the refresh interval happens.

Example, showing images for:
1. The default filters on the demo site
2. Editing one of the filters
3. The spinning that occurs when the user presses enter after editing. This appears to last until the refresh interval, so it's more noticeable when a longer refresh interval (like 70s) is set.

![20200620-karma_refresh_issue](https://user-images.githubusercontent.com/8094490/85210576-07810a00-b30f-11ea-9a75-a7bbb2d1e86c.png)

This affects Karma v0.64.  On the last Karma release, v0.63, editing a filter like this immediately refreshes the displayed alerts when the user presses enter.

This was tested locally and on the demo site (https://karma-demo.herokuapp.com/).

Tested on Chrome (83.0.4103.97) and Firefox (77.0.1)

Thank you!!!

**Comment by prymitive** [comment]
#1872 should fix that, thanks!
