### ISSUE TITLE
Make background color configurable

### ISSUE THREAD

**Issue by sylr** [prymitive/karma#189]
It would be nice if we could set the background color back to which Unsee is using :)

**Comment by prymitive** [comment]
This is the type of feature requests that I'm a bit skeptical about. UI customization adds extra complexity which is usually not very valuable and while one person might want to customize background color other want to change navbar, font size and so on, which is hard to test for when designing the UI.
The most I'm willing to add is a way to inject custom css & js with no guarantee for retaining class names between releases. It means that there would be `/custom.css` & `/custom.js` files inside docker image that you can overwrite with whatever you want, you can use that to add

```css
body {
  background-color: "foo";
}
```

Would that work for you?

**Comment by prymitive** [comment]
Raised #190 with support for that

**Comment by prymitive** [comment]
Merged #190, see https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#customizing-karma for docs on it
