### ISSUE TITLE
Alert not showing in interface

### ISSUE THREAD

**Issue by felskrone** [prymitive/karma#1914]
Hi, 

I have been using karma for a couple weeks now and so far everything is working fine. 

From the beginning i setup a DeadmanSwitchAlert to ensure, that the alerting pipeline is fully functional.

Karma pulls the alerts from 4 alertmanager instances A,B,C,D and all 4 emit the DeadmanSwitchAlert, but only three are showing in karma.

So far i verified that
- all prometheus instances have that alert as "firing"
- all alertmanagers have the alert as firing as well
- all alertmanagers actually return the DeadmanSwitchAlert via their api from http://alertmanager:9093/api/v2/alerts
- i dont have any silences showing in karma and none in the alertmanagers as well

The DeadmanSwitchAlert returned by all alertmanagers look like this:

```bash
[
    {
        "annotations": {
            "description": "vector(1)",
            "summary": "Hive803 alerting pipeline is working!",
            "title": "DeadManSwitch Hive803"
        },
        "endsAt": "2020-07-01T06:56:31.281Z",
        "fingerprint": "b5d6bd9361681a6c",
        "receivers": [
            {
                "name": "slack_cse"
            }
        ],
        "startsAt": "2020-06-29T13:03:31.281Z",
        "status": {
            "inhibitedBy": [],
            "silencedBy": [],
            "state": "active"
        },
        "updatedAt": "2020-07-01T06:53:31.682Z",
        "generatorURL": "http://prometheus:9090/graph?g0.expr=vector%281%29\u0026g0.tab=1",
        "labels": {
            "alertname": "DeadMansSwitch",
            "hive": "DeadManSwitch",
            "location": "fra",
            "severity": "info",
            "site": "fra",
            "team": "CSE"
        }
    }
]
```

They only differ in the unique fields like startsAt, updatedAt, etc.

So the DeadmanSwitchAlert from A,B and C are showing, D is missing. 

The weird thing is, that the other alerts from alertmanager D are showing just fine.

I have already deleted and redeployed the stack several times.
Im not using any static volumes for karma.

My karma.yml only contains for entries like this one

```bash
alertmanager:
  interval: 60s
  servers:
    - name: instancename
      uri: https://user:password@alerts.<mydomain>.com
      timeout: 10s
      proxy: true
      readonly: false
...
```
My karma-version is 0.63.

Any hint on how to debug this further is appreciated.

**Comment by prymitive** [comment]
Anything in karma logs?
Logs should show how alerts it’s collecting from each alertmanager. If you don’t have any other alerts it should be 1 for each alertmanager.

**Comment by felskrone** [comment]
No errors in the karma logs. e804 is the alertmanager instance that emits the DeadmanSwitchAlerts that is not showing.

```bash
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Upstream version: 0.20.0"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Got 0 silences(s) in 7.900467ms"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Detecting ticket links in silences (0)"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Got 8 alert group(s) in 20.377763ms"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Deduplicating alert groups (8)"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Processing unique alert groups (8)"
Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Merging autocomplete data (184)
```

The json is rather large and contains sensitive data, so i wrote 10 linee to show the number of alerts currently firing by alertname:

```bash
import json
import pprint

d = json.loads(open('test2.json').read())

counts = {}

for entry in d:
    for alarm, props in entry.items():
        if alarm == "labels":
            counts.setdefault(props['alertname'], 0)
            counts[props['alertname']] += 1
pprint.pprint(counts)
```

It also shows the DeadmanSwitch as active.

```bash
{'DeadMansSwitch': 1,
 'network_device_unreachable': 28,
 'network_device_unreliable': 28,
 'stale_collector_files': 1,
 'task_high_cpu_usage_50': 1,
 'unexpected_service_count': 1,
 'unexpected_stack_count': 1}
```

**Comment by felskrone** [comment]
Does the debug-logging not show more information when pulling alarms from alertmanagers?

I set log->level->debug and i can see messages with that level, but it does not show any more info for the pulling/parsing the alarms.

**Comment by prymitive** [comment]
`Jul 01 10:20:22 monitor docker.karma[995]: time="2020-07-01T08:20:22Z" level=info msg="[e804] Got 8 alert group(s) in 20.377763ms"`
How many alerts do you have in alertmanager UI?

`@alertmanager=e804` should show you all alerts from that instance in karma

**Comment by felskrone** [comment]
I figured it out. The annotations are the same for two of the DeadmanSwitchAlerts, they get aggregated into a single alarm but with two alertmanager-labels. The assigned labels are duplicate, sorry for the noise.

Thanks for the quick response!
