### ISSUE TITLE
Display link and text in comment 

### ISSUE THREAD

**Issue by duthifree** [prymitive/karma#1922]
Hi !

Today when we add a ticket reference to comment with `silences:comments:linkDetect:rules` feature, a link to the referred ticket are displayed on the silence.

it's a very cool feature, but is there a way to add some text to this comment and display a ticket link ?

we could then use `ACK!` feature and `kthxbye` deamon and add ticket link by editing silence 

regards

**Comment by prymitive** [comment]
you can have as much text in the silence comment as you need, it doesn't need to be just the ticket id (example: `JIRA-1234 some text`)

**Comment by duthifree** [comment]
Yes, but i lose the linkdetect feature ?

**Comment by prymitive** [comment]
No, it should detect substrings

**Comment by prymitive** [comment]
It should but it doesn't  - http://karma-demo.herokuapp.com/?q=%40cluster%3DHA&q=%40receiver%3Dby-cluster-service&q=alertname%3DSilenced%20Alert%20With%20Jira%20Link

Need to fix this

**Comment by prymitive** [comment]
Accidently broke it a while ago by anchoring regex rules, should be fixed ince ^ PR gets merged

**Comment by duthifree** [comment]
Many thanks !!!
