### ISSUE TITLE
Link to alert 'source' to graph over time of rule data

### ISSUE THREAD

**Issue by warmfusion** [prymitive/karma#2025]
On alertmanagers UI, there is a button to quickly take me to the source of a given alert and to view the graph over time for the event.

It is possible to get something similar on Karma, so that when i have an alert of 'High 500 rate on Ingress` I can quickly view that data over time from the Prometheus UI?

Cheers

**Comment by prymitive** [comment]
When you click on individual alert menu there are source links from alert JSON:

<img width="246" alt="Screenshot 2020-08-07 at 14 14 46" src="https://user-images.githubusercontent.com/114288/89649256-5c291600-d8b8-11ea-91c3-c56cf1bfc913.png">

Is that what you're after?

**Comment by warmfusion** [comment]
Well look at that! Thats what I was looking for, just hidden away a little.

Thanks!
