### ISSUE TITLE
Can you add a pause button?

### ISSUE THREAD

**Issue by faceair** [prymitive/karma#2057]
Sometimes the page automatically refreshes when I'm viewing the alert's details, which interrupts my troubleshooting.

![image](https://user-images.githubusercontent.com/3659110/90130469-1929df80-dd9d-11ea-8b59-8364bc3d602a.png)

Can you make this pause button always show and support click ? Make this like a play button.

**Comment by prymitive** [comment]
How about a global keyboard shortcut? Like `ctrl+space` or something?

**Comment by faceair** [comment]
Shortcuts are not easy to remember and use, or take a look at grafana's drop-down box for the refresh button.

![image](https://user-images.githubusercontent.com/3659110/90137452-39ab6700-dda8-11ea-9da0-3b509da33f4a.png)

**Comment by prymitive** [comment]
hovering mouse over the countdown indicator will show a pause button now

**Comment by faceair** [comment]
Very nice animation !

![image](https://user-images.githubusercontent.com/3659110/91259726-a14ab480-e7a1-11ea-8a58-79e6686d8f11.png)
