### ISSUE TITLE
Use ENTRYPOINT instead of CMD in Dockerfile

### ISSUE THREAD

**Issue by dannyk81** [prymitive/karma#21]
Hey!

First of all this tool is totally dope! thanks 🙌 

Small request, it would be great if you could change the Dockerfile to use `ENTRYPOINT` instead of `CMD`, this would make things much simpler in terms of passing cmd line arguments to the container, as these are set into `CMD` and are appended by default to `ENTRYPOINT`.

Thanks!

**Comment by prymitive** [comment]
I keep getting confused by some duplicated docker options like `ADD` vs `COPY` and `CMD` vs `ENTRYPOINT` but I think you're right that `ENTRYPOINT` allows easier runtime customization so we should use that instead of `CMD`.
