### ISSUE TITLE
Extend "click to expand/collapse" action on the whole alert group header?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#2106]
Hi,
thank you for Karma! When expanding (or collapsing) alerts I wish the area to do so would be bigger instead of the caret only on the right hand side. Perhaps the whole alert group header should be clickable to expand/collapse, what do you think?

**Comment by prymitive** [comment]
IMHO given that the header contains clickable elements having it all clickable would increase the chance of miss-clicks.
I'd rather expand the area around those icons so they are proper buttons.

**Comment by filippog** [comment]
Good point re: misclicks, increasing the expand/collapse button area SGTM!
