### ISSUE TITLE
Favicon badge readabilty

### ISSUE THREAD

**Issue by dmke** [prymitive/karma#2107]
The alert count is very hard to read:

- Firefox 80: ![image](https://user-images.githubusercontent.com/327411/91309038-6a2fcf80-e7b0-11ea-88f7-ca03789630e0.png)
- Chrome 85 beta: ![image](https://user-images.githubusercontent.com/327411/91309297-b418b580-e7b0-11ea-90b8-8f34cc6b4ab8.png)

On Chrome 84 (stable), it looks OK, however I'm migrating away from Chrome: ![image](https://user-images.githubusercontent.com/327411/91309399-d90d2880-e7b0-11ea-8f58-31e2767ba083.png)

Those screenshots made are all on my Debian workstation (no HiDPI monitor).

It becomes readable, if I remove the following line:

https://github.com/prymitive/karma/blob/11658f4bbe55094666fd431ca1f3ca95fbfe170f/ui/src/Components/FaviconBadge/index.tsx#L19

<details><summary><s>Would you accept a PR to change this line to something like this?</s></summary>

This won't help in Firefox, at all...

```diff
@@ ui/src/Components/FaviconBadge/index.tsx
-    fontStyle: "lighter",
+    fontStyle: window.devicePixelRatio > 1 ? "lighter" : "normal",
```

</details>

Addendum: This is how it looks in Firefox 80 my HiDPI monitor (`window.devicePixelRatio === 2`):

![image](https://user-images.githubusercontent.com/327411/91349873-366f9c80-e7e6-11ea-8ba1-61bb889476ff.png)

**Comment by dmke** [comment]
N.B. As you can see in the Firefox image above, the `favicon.ico` is hard to recognize when using the browser's dark theme. Maybe a white outline could help here, or replace the icon with an inverted one, as suggested [here](https://stackoverflow.com/a/55252008/766783)?

**Comment by prymitive** [comment]
I'll look into adding a favicon that works better with dark mode

**Comment by prymitive** [comment]
Having a dedicated icon for dark mode looks tricky and the result varies depending on the browser, so I've updated favicon to have a solid background, this should make it more look decent in both and be more readable in dark mode.

**Comment by dmke** [comment]
That works for me.

I have the Karma and Prometheus tabs pinned right beside each other anyway, so for me it's less of a problem :-)
