### ISSUE TITLE
Unable to create silence in Karma Dashboard throws "Failed to fetch" error

### ISSUE THREAD

**Issue by jaisegrg** [prymitive/karma#2189]
Hi @prymitive 

I am unable to create silence in Karma Dashboard throws "Failed to fetch" error.
Can you please help on this?

Thank you,
Jaise George

**Comment by prymitive** [comment]
Check browser console "Developer Tools" on Chrome, it should have logs for the error causing this

**Comment by jaisegrg** [comment]
@prymitive ,

Below is the error, 

Access to fetch at '' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

**Comment by prymitive** [comment]
HTTP responses have `Access-Control-Allow-Origin: *` header set which is not allowed by browsers.

See `cors:credentials` on https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#alertmanagers
and https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for context.

Either get rid of that header (karma doesn't set it) or adjust your `cors:credentials` setting.

**Comment by jaisegrg** [comment]
@prymitive,

Thank you for the help!!

I have set the below values in confgmap and issue got resolved.

cors:
        credentials: omit
