### ISSUE TITLE
Single flag to specify configuration file path and no need to append .yaml (please...)

### ISSUE THREAD

**Issue by dannyk81** [prymitive/karma#22]
It would be great if we could specify the path to the configuration file in a single command flag (instead of using two), e.g.:

```
$ karma --config.file /etc/karma/karma.yaml
```

We've also noticed that karma is appending a `.yaml` suffix to the file name we provide, which is a bit counter-intuitive, especially with yaml as some prefer `.yml` (like in our case 😄) while others use `.yaml`

Again, thanks!!!

**Comment by prymitive** [comment]
Yeah, flag set way is awkward at best

**Comment by prymitive** [comment]
`config.file` is now the only flag and it takes full path
