### ISSUE TITLE
silenceForm.author.populate_from_header variables no longer needed?

### ISSUE THREAD

**Issue by candlerb** [prymitive/karma#2246]
This feature was removed in e9306d22 (replaced with `authentication`).  However there is still code for the environment variables [here](https://github.com/prymitive/karma/blob/master/internal/config/config.go#L194):

```
                case "SILENCEFORM_AUTHOR_POPULATE_FROM_HEADER_HEADER":
                        return "silenceForm.author.populate_from_header.header"
                case "SILENCEFORM_AUTHOR_POPULATE_FROM_HEADER_VALUE_RE":
                        return "silenceForm.author.populate_from_header.value_re"
```

Should these also go?

**Comment by prymitive** [comment]
Yes, will be fixed via #2257. Thanks
