### ISSUE TITLE
exclude labels (namespace) from Aggregation and Deduplication

### ISSUE THREAD

**Issue by wuestkamp** [prymitive/karma#2280]
Is it possible to only aggregate and deduplicate by one label, like `alertname`?

Right now we have multiple alerts shown with the same `alertname` because they have different `namespace` labels.

**Comment by prymitive** [comment]
You can control how alerts are grouped by adjusting your alertmanger [routing tree](https://prometheus.io/docs/alerting/latest/configuration/#route) and setting `group_by` to whatever works best for you. If you want to have different `group_by` in karma then you have in alerts routed to other services (like PagerDuty, email, etc) then I suggest to have a dedicated receiver for karma in alertmanager config with group_by tweaked to how you want alerts to appear there. Once you do that you can configure karma to ignore other [receivers](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#receivers).

**Comment by wuestkamp** [comment]
This works great, thanks!
