### ISSUE TITLE
Improve support for clustered Alertmanagers

### ISSUE THREAD

**Issue by dswarbrick** [prymitive/karma#229]
When multiple Alertmanagers are configured in Karma, they are treated as separate standalone instances, even if they are part of an HA cluster. This has the disadvantage that when creating silences, it is by default sent to all configured Alertmanagers.

By design, such HA Alertmanagers will propagate the silence via gossip, and it ends up being duplicated. 

When Karma then scrapes e.g. two Alertmanagers that are part of a cluster, it sees two silences from _each_ Alertmanager, and ends up displaying four silences. I expect that this will multiply, so 3 Alertmanagers would show 9 silences, 4 Alertmanagers would show 16, and so on.

**Comment by prymitive** [comment]
All valid points. HA mode support is definitely "not great" and needs improvements, which is on my TODO list. The biggest blocker here is the amount of refactoring that needs to happen, so it should happen soonish but will take a few weeks at least.

**Comment by prymitive** [comment]
```
By design, such HA Alertmanagers will propagate the silence via gossip, and it ends up being duplicated.

When Karma then scrapes e.g. two Alertmanagers that are part of a cluster, it sees two silences from each Alertmanager, and ends up displaying four silences. I expect that this will multiply, so 3 Alertmanagers would show 9 silences, 4 Alertmanagers would show 16, and so on.
```

This is a bit unclear to me. Silences are propagated which means you should only see 1 silence per alertmanager, it will be duplicated but it's still going to be 2x, not 4x.
It looks like you might be creating silences in both alertmanager instances separately which results in 4x.

**Comment by dswarbrick** [comment]
> This is a bit unclear to me. Silences are propagated which means you should only see 1 silence per alertmanager, it will be duplicated but it's still going to be 2x, not 4x.
> It looks like you might be creating silences in both alertmanager instances separately which results in 4x.

The problem is that if you open the context menu of an alert group in Karma and select "Silence this group", by default it opens a silence form that has all alertmanagers that are currently firing that alert. So when you commit that silence, it is creating individual silences on each of the alertmanagers, which then propagate each silence amongst themselves, resulting in the duplication.

**Comment by prymitive** [comment]
Good point, that needs fixing as well

**Comment by prymitive** [comment]
- [ ] Silence form should use cluster list instead of instances
- [ ] Silences should be stored per cluster

**Comment by prymitive** [comment]
Merged a bunch of changes to improve HA support, not very pretty so I'll need to do some cleanups on the backend side eventually as the current code there is not great.
