### ISSUE TITLE
Relocate Helm Chart

### ISSUE THREAD

**Issue by svenmueller** [prymitive/karma#2347]
Hi,

Is anyone looking into relocating the current Helm chart from repo  ttps://charts.helm.sh/stable into a new location? The old stable/incubator repos might be gone at any time after Helm v2 EOL (charts are archived though, https://helm.sh/blog/charts-repo-deprecation/).

-- Sven

**Comment by prymitive** [comment]
No idea, I don't use Helm charts.
The whole concept feels to me like translating one set of YAML schemas to another set of YAML schemas in what appears to be endless loop of YAML. My gut feeling is that everyone should maintain their own charts or wait for another solution for templating k8s manifests. Not really a problem I want to solve.
🤷

**Comment by mtmn** [comment]
@prymitive - I can take a look at this one.

**Comment by prymitive** [comment]
I'm not sure what is there to look here, you might want to get in touch with the creator of the Helm Chart - https://github.com/helm/charts/pull/8143

**Comment by steinbrueckri** [comment]
Any update?
