### ISSUE TITLE
Version v0.76 reports as "dev"

### ISSUE THREAD

**Issue by MeierBR** [prymitive/karma#2479]
I just installed the version v0.76. In the settings popup it reports version "dev"
![image](https://user-images.githubusercontent.com/72253578/100450257-9d3a7580-30b5-11eb-9c87-9f872a7f96d3.png)

snippet from k8s deployment: 
```    spec:
      containers:
      - env:
        - name: CONFIG_FILE
          value: /etc/karma/karma.conf
        image: lmierzwa/karma:v0.76
        imagePullPolicy: IfNotPresent
```

**Comment by prymitive** [comment]
I moved docker builds to use Github actions and looks like version is not passed properly anymore, should be easy to fix (#2480). Thanks!
