### ISSUE TITLE
Release v0.76 prefixes paths with artifacts/ in sha512sum.txt

### ISSUE THREAD

**Issue by BenoitKnecht** [prymitive/karma#2490]
I'm not sure if this is intentional:

```console
$ curl -sL https://github.com/prymitive/karma/releases/download/v0.74/sha512sum.txt | awk '/karma-linux-amd64.tar.gz/ { print $2 }'
karma-linux-amd64.tar.gz
$ curl -sL https://github.com/prymitive/karma/releases/download/v0.76/sha512sum.txt | awk '/karma-linux-amd64.tar.gz/ { print $2 }'
artifacts/karma-linux-amd64.tar.gz
```

The change broke the Ansible playbook I was using to deploy Karma. It's not necessarily an issue in and of itself, as it's pretty easy to fix in Ansible (although I do prefer the old format), but I'd like to know which format is going to be used for future releases.

**Comment by prymitive** [comment]
Fixed github action so it shouldn't add `artifacts/` anymore, thanks!
