### ISSUE TITLE
Multiple karma - gridsort order configuration bleeds over

### ISSUE THREAD

**Issue by xkilian** [prymitive/karma#2534]
Is there a way to specify for a given Karma the grid sort order based on a label. 
Answer that I know: Yes, in the UI in the configuration.

Unfortunately, when accessing a second Karma with the same browser, the setting is applied to the second instance of Karma. The two Karma instances have different users and need different grid sorting.

 Is this preference stored in a Cookie?
Is there a way to have a unique cooki per Karma instance, or force the setting in the configuration file?

**Comment by prymitive** [comment]
Configuration is saved to browsers localStorage -  https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage. There should be no problem in hosting multiple instances as long as each has a unique domain (`karma1.example.com` and `karma2.example.com`). If you are using two instances on the same domain but different root uri then I think they will share same browser localStorage data.
https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#ui-defaults tells you how to configure UI defaults in the config file.

**Comment by xkilian** [comment]
Ok, we are using www.domain.com/karma and www.domain.com/division2/karma.
