### ISSUE TITLE
Alt+Click filtering doesn't work on Linux

### ISSUE THREAD

**Issue by tbregolin** [prymitive/karma#2536]
The Alt+Click shortcut to filter out a label does not work on Firefox, on Linux, because it opens the menu bar. Can this be configurable or based on the user agent?

**Comment by prymitive** [comment]
I'm running Fedora and alt+click works for me in Firefox.

**Comment by tbregolin** [comment]
Ah, I see. Thank you for checking.

Many of the popular window managers (Gnome's, KDE's, Xfce's, Mint's, Openbox, etc) have historically used "Alt + Left Click" to drag windows: https://www.google.com/search?&q=linux+alt-click. I had tried disabling ui.key.menuAccessKeyFocuses in Firefox and the binding in the window manager, but it turns out I hadn't disabled all of necessary ones. If I turn them all off, it works.

I can live with some remapping, so it's up to you if you want to appease the use case or not. Feel free to close.

**Comment by prymitive** [comment]
I might be able to add shortcut configuration if it’s easy enough, need to look into it.
Would be a good place to learn all shortcuts

**Comment by tbregolin** [comment]
I managed to add this with some search-and-replace: https://github.com/prymitive/karma/commit/b15b8511e40ce0c711571cc43564d108886bbbee

It works but, as you can tell, I don't know TypeScript, so it looks funny.

**Comment by fernferret** [comment]
Hey @prymitive I'm suffering from this issue mainly to my addiction to using the alt key to move my windows. I use MATE which by default sets up the alt key for window moves (as mentioned).

I was able to turn this off and confirm as @tbregolin did that MATE was indeed eating these mouse events.

I'd totally be willing to make a PR but it looks like @tbregolin already hashed a solid amount of this out a while ago. Not sure if they're still interested in pursuing it but I'd be interested in supporting this pull if folks are able to review it (I'm willing to take over if it's no longer active). The linked commit looks reasonably complete, maybe just need to [update some tests like this one](https://github.com/prymitive/karma/blob/main/ui/src/Components/Labels/FilteringLabel/index.test.tsx#L45) (and the rest of course) to support the config params.

If you're willing to review and merge, I'm absolutely willing to do some work on this to get it to the finish line.
