### ISSUE TITLE
need to strip karma tag

### ISSUE THREAD

**Issue by duthifree** [prymitive/karma#2561]
hi,

i would like to strip karma tag (label prefixed by @)
example this one "@cluster"

how can i do ?

**Comment by duthifree** [comment]
any advice ??

**Comment by prymitive** [comment]
`@cluster` is needed to differentiate between different alertmanager clusters when there are multiple defined in karma config. It's not visible if you have only one alertmanager cluster configured, so if you don't want to see it spin up multiple karma instances, one per each alertmanager cluster.

**Comment by duthifree** [comment]
Ok :'(

Thx for your reply
