### ISSUE TITLE
Strip labels doesn't work when alertmanager has no group_by

### ISSUE THREAD

**Issue by timown** [prymitive/karma#2577]
hey,

we are using karma 0.78 and alertmanager 0.21.0,
in alertmanager we have `group_by: ['...']` configuration, as a results in the `alerts.json` each alert arrives as a separate entry in alertGroups with all the labels being on the group level and nothing on the `alerts`

```json
"alertGroups": [    
    {
        "receiver": "alerts",
        "labels": {
            "alertname": "KubeContainerWaiting",
            "container": "tester",
            "namespace": "jobs",
            "pod": "samples-mega-build-pull24-1608796616-ext-images-plzvj",
            "prometheus": "monitoring/prometheus-operator-kube-p-prometheus",
            "reason": "ImagePullBackOff",
            "severity": "warning"
        },
        "alerts": [
            {
                "annotations": [
                    {
                        "name": "description",
                        "value": "Pod jobs/samples-mega-build-pull24-1608796616-ext-images-plzvj container tester has been in waiting state for longer than 10 minutes, caused by ImagePullBackOff.",
                        "visible": true,
                        "isLink": false
                    },
                    {
                        "name": "summary",
                        "value": "Pod container waiting longer than 10 minutes.",
                        "visible": true,
                        "isLink": false
                    }
                ],
                "labels": {},
                "startsAt": "2020-12-24T08:29:36.722Z",
                "state": "active",
                "alertmanager": [
                    {
                        "fingerprint": "691218dc83278da6",
                        "name": "alertmanager.root.io",
                        "cluster": "alertmanager.root.io",
                        "state": "active",
                        "startsAt": "2020-12-24T08:29:36.722Z",
                        "source": "http://prometheus.root.io/...",
                        "silencedBy": [],
                        "inhibitedBy": []
                    }
                ],
                "receiver": "alerts",
                "id": "e59744063f4e363cb1f05e3334267145e4f86c81"
            }
        ],
        "id": "f6598cda30759b4a9939cd2300f73f90190845b4",
        "alertmanagerCount": {
            "alertmanager.root.io": 1
        },
        "stateCount": {
            "active": 1,
            "suppressed": 0,
            "unprocessed": 0
        },
        "shared": {
            "annotations": [],
            "labels": {},
            "silences": {}
        }
    }
]
```

from a quick glance looks like adding
`ag.Labels = transform.StripLables(config.Config.Labels.Keep, config.Config.Labels.Strip, ag.Labels)`

before Hash in https://github.com/prymitive/karma/blob/master/internal/alertmanager/dedup.go#L91 might solve this

Another question is if it's possible to achieve the same view as having `group_by: ['alertname']` in alertmanager (while leaving it `group_by: ['...']`) with a setting on karma level?

**Comment by prymitive** [comment]
I'm not sure if I understand the problem with stripping labels, which label are you trying to strip that is not being stripped in the UI?

> Another question is if it's possible to achieve the same view as having group_by: ['alertname'] in alertmanager (while leaving it group_by: ['...']) with a setting on karma level?

Send it to a different receiver in alertmanager, you can set a different group_by there.
You can then use https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#receivers to have only that one receiver in karma.

**Comment by timown** [comment]
In this case we are stripping `prometheus ` but because alertmanager has a configuration of `group_by: ['...']` when karma queries for `alerts.json` as you can see in my post there are no labels on alert level and all the labels arrive on alertGroups labels, those are not stripped

**Comment by timown** [comment]
> Send it to a different receiver in alertmanager, you can set a different group_by there.
> You can then use https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#receivers to have only that one receiver in karma.

this actually solves both our issues, thanks @prymitive!
