### ISSUE TITLE
external_labels not handled by karma

### ISSUE THREAD

**Issue by Stono** [prymitive/karma#2585]
Hello!
I have a tiered prometheus setup and use `external_labels` in prometheus to annotate metrics with the source prometheus like this:

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    origin_prometheus: prometheus01
```

You can see here this gives me an `origin_prometheus` label:
<img width="417" alt="Screenshot 2020-12-29 at 10 27 57" src="https://user-images.githubusercontent.com/1486729/103277270-8b076c00-49c0-11eb-8665-a4ca56184b14.png">

I have the following configuration which i would hope hides this label (as it isn't relevant for karma users), but it doesn't appear to work:
```
labels:
  keep:
    - "severity"
    - "source"
    - "group"
```

If it helps to debug, i'm also not able to filter by the label:
<img width="1066" alt="Screenshot 2020-12-29 at 10 30 07" src="https://user-images.githubusercontent.com/1486729/103277425-d9b50600-49c0-11eb-8f75-a04c0fd7b5b9.png">

You can see it in alertmanager:
<img width="783" alt="Screenshot 2020-12-29 at 10 30 46" src="https://user-images.githubusercontent.com/1486729/103277458-efc2c680-49c0-11eb-9865-d888f8befa84.png">

I'm using the latest version of both karma and alertmanager.

Thanks

**Comment by prymitive** [comment]
Labels were stripped from alerts, but not from group objects. Should be fixed via #2586

**Comment by Stono** [comment]
Thanks @prymitive - will give it a test tomorrow!

**Comment by Stono** [comment]
@prymitive thank you, this also fixed: https://github.com/prymitive/karma/issues/1881
