### ISSUE TITLE
Custom alerts actions in dropdown menu?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#2596]
Hello,
thanks for your work on karma!

In the karma deployment we have it is somewhat common to create tasks/issues from an alert for further followup. A "click here to create a new task for this alert" is possible today via annotations (i.e. creating a task is an HTTP GET) but unwieldy (i.e. having to attach the same annotation when defining alerts).

I was wondering if there's interest in having this feature in karma itself? Namely sth like being able to define (templated) links that will show up in the alert's dropdown, alongside "alert source links" and "silence this alert" actions. What do you think ?

thanks again!

**Comment by prymitive** [comment]
Being able to move some annotation links to the actions menu might be a nice way of decluttering  the UI when there's plenty of them.

**Comment by filippog** [comment]
Yes I think moving some annotations to the drop down is going to be nice. What do you think re: adding also custom actions from karma configuration itself ?

**Comment by prymitive** [comment]
Can you give me an example of such action?

**Comment by filippog** [comment]
Any action that's likely common to all alerts would fit the bill I think, e.g. "open a new task". The advantage of having the configuration in Karma itself (in addition to be able to turn annotations into drop-down actions) would be that common actions don't need to be added as annotations to all alerts. Hope that makes sense!

**Comment by prymitive** [comment]
How would you define "open a new task" action? Is that a link to something?

**Comment by filippog** [comment]
That's correct, for example in phabricator you can build URLs to create a new task, with fields pre-filled via query string [https://www.mediawiki.org/wiki/Phabricator/Help/Task_Creation_URL](example). I'm assuming similar systems have the same capability.

A different but related example might be "escalate this alert" to e.g. create a new incident from the alert in tools like pagerduty.

Hope that helps!

**Comment by prymitive** [comment]
On one hand you can add annotation links. On the other, as you point out, doing so for all alerts might be a bit of toil.
My only concert is that a global action link might not be useful enough and soon someone will request a way to template it, and then we're back to generating links from labels, which one can already do via annotations.

**Comment by filippog** [comment]
I see what you are saying re: templating within Karma (and in fact that's what I had in mind originally). I'd be happy too with what you suggested, namely being able to move certain annotations into the drop-down menu. I think that'd be already a very good step in the right direction!

**Comment by prymitive** [comment]
Added new option for moving annotations into dropdown menu, example:

```
annotations:
  actions:
    - docs
    - jira
 ```
