### ISSUE TITLE
Healthcheck alert still displayed as regular alert

### ISSUE THREAD

**Issue by BenoitKnecht** [prymitive/karma#2614]
I just tried the new healthcheck feature introduced in #2546, and while it does work as intended when the healthcheck alert is missing, I was surprised to see that the healthcheck alert is displayed in the UI as any other alert (and counted in the favicon counter too) when it's present.

Since it's an alert that is supposed to always be firing, I think it would make sense to hide it by default. Otherwise it distracts from more relevant information.

@felskrone Have you tested this feature too? Are you experiencing the same behavior?

**Comment by secustor** [comment]
I can confirm this behavior and it would be a great addition.

**Comment by prymitive** [comment]
One solution would be to route such alerts to a receiver that you don't have in your default view.
Another possibility is adding a filter that uses same matchers as healthchecks so you an filter it out.
There could be a flag in the config to strip anything that matches too.

**Comment by BenoitKnecht** [comment]
While it's true that this can be worked around with an explicit filter, I still think it would make sense to filter those alerts out by default (and make the filter invisible to the end-user). I cannot think of a situation where you'd want to see dead man's switch alerts displayed.

And it would prevent the healthcheck and filter from accidentally becoming out of sync if the configuration is modified in one section and not the other.

**Comment by BenoitKnecht** [comment]
@prymitive I finally figured out that you meant I could use the [receivers](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#receivers) option to strip the healthcheck alert sent to that receiver entirely. In my mind, the only option was to use a [filter](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#filters) on `@receiver!=`, which I didn't like because it would make it visible to the end-user.

So I far as I'm concerned, there's a good solution to my initial issue, and maybe a simple hint in the documentation is enough. Let me know what you think.

**Comment by prymitive** [comment]
So far I'm leaning towards adding a config flag to hide those alerts from the UI plus expanding docs to suggest routing them to a dedicated receiver (if someone wants to keep them).

**Comment by prymitive** [comment]
Merged #2639 that adds `healthcheck:visible` option (off by default).
