### ISSUE TITLE
strip empty labels

### ISSUE THREAD

**Issue by piif** [prymitive/karma#2640]
I use some alerts with labels dynamically set and sometimes, some of them are empty.
There are configuration options to hide/strip labels by name, bot not by their value.

Is it possible to display them only if there value isn't empty ?

**Comment by prymitive** [comment]
No it's not possible.

**Comment by piif** [comment]
But can you plan it in future versions, or is there a good reason to not implement it ?

**Comment by prymitive** [comment]
I think that the obvious solution is to fix whatever generates those labels, rather then trying to workaround downstream.

**Comment by piif** [comment]
For example, consider a modified version of this kubernetes standard alert :
```
    - alert: KubePodCrashLooping
      expr: |-
        rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m])
        * on(namespace, pod) group_left(label_my_useful_tag)
        kube_pod_labels
        * 60 * 5 > 0
      my_tag: '{{ if $labels.label_my_useful_tag}}{{ $labels.label_my_useful_tag}}{{ end }}'

```
With or without the embedded `if`, if the alert is thrown by a pod which don't have `my_useful_tag`, I obtain a empty value, and i don't see how to filter out this label without defining the alert twice (or factorial(number_of_optionnals_labels) ...)

It's just a "cosmetic" problem, but I don't see how to solve it :
![image](https://user-images.githubusercontent.com/5402713/105344599-6ed3a500-5be3-11eb-8f3b-25a8ba607d75.png)

**Comment by piif** [comment]
As a workaround which could be useful for other usages, you may consider a "style" or "class" directive, in addition to "color" one to add css styles or classes to items.
Then users may affect them to "display:none" or any other css directives

**Comment by prymitive** [comment]
I still unconvinced that this sort of feature is unnecessary.

Looking at your alert it seems obvious to me that the only problem is that the rule trying to inject dynamic tags in a config file that's not really suitable for it.

There are 2 workarounds I could think of:
1. stop adding `my_tag` manually, if it's done just to rename some label (from `label_my_useful_tag` to `my_tag`) then why not use `label_my_useful_tag`? Especially that `label_my_useful_tag` will be there anyway.
2. create 2 alerts, after all you can have as many alert rules with the same name as you want, create one that matches metrics with `label_my_useful_tag` and one that matches metrics without it, and then inject `my_tag` where you know `label_my_useful_tag` is present:

```
    - alert: KubePodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", label_my_useful_tag=""}[15m]) * 60 * 5 > 0
     
    - alert: KubePodCrashLooping
      expr: |-
        rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", label_my_useful_tag=~".+"}[15m])
        * on(namespace, pod) group_left(label_my_useful_tag)
        kube_pod_labels
        * 60 * 5 > 0
      my_tag: '{{ $labels.label_my_useful_tag}}'
```
