### ISSUE TITLE
cant seem to silence or update silenced alerts

### ISSUE THREAD

**Issue by dgsus** [prymitive/karma#2671]
hi, apart from silencing alerts (or editing/deleting current silenced alerts)everything else is fine.

when i try to either create a new one or edit an existing one (deleting as well) , i always get the error:
NetworkError when attempting to fetch resource.

(if i do via alertmanager directly it works)

the log file doesnt show any errors or warnings...any help is appreciated, thanks!

![image](https://user-images.githubusercontent.com/30906366/105736811-1ecf4800-5f2d-11eb-881c-e9599f83a74e.png)

**Comment by prymitive** [comment]
The error comes from the browser, so I would check your browser console log for errors.

**Comment by dgsus** [comment]
ahh i see why, because im using karma behind a proxy

![image](https://user-images.githubusercontent.com/30906366/105742910-fbf46200-5f33-11eb-88e3-d4fcfc1d5183.png)

it seens that we are the ones doing the silence directly and not karma via a "backend" correct?

thanks in advance and thank you for your quick reply!

**Comment by prymitive** [comment]
URLs used to do various tasks are documented on https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md#alertmanagers

**Comment by dgsus** [comment]
ah right, since i have exposed via proxy alertmanager i used the --alertmanager.external_uri and it works now.

thanks for your quick help!!!
