### ISSUE TITLE
Rich annotations are not rendering properly

### ISSUE THREAD

**Issue by BenoitKnecht** [prymitive/karma#2886]
Looking at the [Rich Annotations alert on the demo website](https://demo.karma-dashboard.io/?q=%40cluster%3DHA&q=%40receiver%3Dby-cluster-service&q=alertname%3DRich%20Annotations), it looks like the HTML annotations are not being rendered properly.

![image](https://user-images.githubusercontent.com/1238084/110910213-5180a480-8311-11eb-95bf-4ed90402e103.png)

At least I assume that the goal was for the HTML to be interpreted rather than escaped, right?

**Comment by prymitive** [comment]
HTML is escaped and rendered raw to avoid any security risk of malicious actor injecting javascript into user browsers.

**Comment by prymitive** [comment]
I'll have a look at what's possible, least we could do is to let people render html if they want to, as long as it's an opt-in

**Comment by prymitive** [comment]
Raised #2978 for that
