### ISSUE TITLE
Custom group_by 

### ISSUE THREAD

**Issue by rlex** [prymitive/karma#2899]
Hello.
In some cases, alertmanager internal grouping needs to be disabled completely using group_by: [...] (opsgenie intergration woes)
This essentially breaks karma, since no grouping creates one element per alert which is not really useful.
Alertmanager UI have custom grouping function, allowing you to set your own group rules for display only.
I wonder if this functionality can be recreated in karma, ie in config, with same syntax
```
group_by:
  - alertname
  - severity
```
Or something like this. Will be really nice feature to have.

**Comment by prymitive** [comment]
If you add a dedicated receiver for karma you'll be able to set whatever group_by works for you.

**Comment by rlex** [comment]
Oh, i hasn't thought about that. Adjusted routes with continue: true and added karma with custom group_by, works great. Thanks!
