### ISSUE TITLE
grouping cards by alert name

### ISSUE THREAD

**Issue by dminca** [prymitive/karma#2980]
Hey there,

Lovely project! Just started using it and I saw in the demo that cards are grouped by `alertname` and `cluster`, do you know how can I achieve the same in my configuration? Is there anything I need to tweak on Karma side or is this related to Alertmanager `group_by` ?

![image](https://user-images.githubusercontent.com/5355219/114144258-6c950300-9915-11eb-9fb0-902d009a4fa5.png)

Also, can I enable the counters in the search filter also? If so, how?

![image](https://user-images.githubusercontent.com/5355219/114144504-afef7180-9915-11eb-8f79-3ddb73a132fc.png)

**Comment by prymitive** [comment]
https://github.com/prymitive/karma#alert-groups

Are you saying it doesn't work for you?

**Comment by dminca** [comment]
I didn't try that on the Alertmanager side, asked because I was not sure where exactly I need to make the changes in order to capture that same result.

But now I know, thank you! 🙏
