### ISSUE TITLE
Multiple alertmanager servers with same uri not allowed

### ISSUE THREAD

**Issue by kubicgruenfeld** [prymitive/karma#3024]
We are using cortex multi-tenant alertmanagers, they are all accessed from within the same uri, but have different configuration and alerts. Alertmanager instances are distinguished between tenants by using a http header (X-Scope-OrgID).
I tried to configure them as seperate alertmanagers in karma configuration but when defining two servers with same uri it errors with:

```
level=fatal msg="Execution failed" error="failed to register Alertmanager 'tenantA' with URI 'http://alertmanager:80/alertmanager': alertmanager upstream 'tenantB' already collects from 'http://alertmanager:80/alertmanager'"
```

I could workaround it for testing by using multiple "/" in the uri, so for the second tenant i configured 'http://alertmanager:80//alertmanager', but this is a bit too hacky.

**Comment by prymitive** [comment]
Removed URI checks via #3026
