### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ltandrei** [prymitive/karma#3028]
Hi,

I'm using Karma for quite some time (2 months) and I start noticing that from time to time the dashboard is throwing an error like this: [**Can't connect to the API, last error was "Unexpected token < in JSON at position 0"**]. Any advice on this?

**Comment by prymitive** [comment]
Browser console under Developer Tools should give you more details as you'll be able to see exact errors and inspect the reponse.

**Comment by ltandrei** [comment]
Was able to find a timeout in querying alertmanager cluster nodes. Thank you, prymitive.
