### ISSUE TITLE
Trigger action at silence or vice versa

### ISSUE THREAD

**Issue by kubicgruenfeld** [prymitive/karma#3065]
Hi,

we are currently using Icinga2 for monitoring and we have implemented to be able to acknowledge alerts in icingaweb2. At acknowledgement there is a ticket created in a ticket system to be able to work on it.

Now we are trying to implement something similar with Alertmanager and I wonder if karma already can be configured similar.

My idea was to use an annotation and the feature implemented in #2860 to be able to create a ticket within the dropdown action. But then you still would need to create a silence (with the ticket id) and i wonder if this can be done by a single click somehow?

**Comment by prymitive** [comment]
I don't think there's a way.
If you want alerts to create tickets then you might want to look at something like https://github.com/prometheus-community/jiralert, or write a custom webhook receiver.

**Comment by kubicgruenfeld** [comment]
Thanks for the reply.
Sure, we could configure a webhook in alertmanager or just use mail to create tickets. But we only want tickets for acknowledged alerts.
That's something you can normally configure in services like opsgenie, but since we can't use us-based external services for this I have a hard time to find an open-source solution.
Wouldn't it be feasible to trigger a link from an annotation at acknowledging?

**Comment by prymitive** [comment]
What do you mean by `trigger a link`? How does that give you `a silence (with the ticket id)`?
Wouldn't that require having some integration with a ticketing system?

**Comment by kubicgruenfeld** [comment]
You're right, it would not. But you could at least create ticket and silence with a single click.

**Comment by prymitive** [comment]
I'm not really interested in maintaining integrations with 3rd party systems other than Alertmanager and Prometheus.

**Comment by kubicgruenfeld** [comment]
Understandable.
But the way I was proposing would be quite general, since users can configure their own action at acknowledgment with links in annotations.

**Comment by prymitive** [comment]
I think you need to explain it a bit more for me to understand.

**Comment by EpiqSty** [comment]
We have a similar case between karma and OpsGenie, basically in case of alerts - both systems needs to be Ack'ed/Silenced and such feature could save some time in case if integration is possible.
