### ISSUE TITLE
listen.prefix error on request without trailing /

### ISSUE THREAD

**Issue by ninlil** [prymitive/karma#3084]
We are hosting our karma-instance behind a nginx-proxy (in kubernetes) and have added the following config:
```yaml
listen:
  prefix: /karma/
```
This works just fine, except when requesting "http(s)://hostname.domain/karma"
Then we get requests to  "/static/js/..." and "/custom.css" among others, thus resulting in a white page.

**Comment by prymitive** [comment]
#3085 should fix that
