### ISSUE TITLE
Query filtering in URL is broken

### ISSUE THREAD

**Issue by v0lk3r** [prymitive/karma#3095]
If I filter on a label karma properly filters *and* updateds to URL, adding the query like so:
https://karma.example.com/#/alerts?q=@receiver!=devnull (URL is escaped in reality, I skipped that for clarity here). If I then reload the browser page the query is not applied and the URL is reset.

This makes it impossible to link to karma with some filter applied.

How to reproduce:
* load karma in the browser
* filter by clicking on any label
* check that the URL gets updated
* reload that new browser URL
* now the filter will be reset (which is the bug)

**Comment by prymitive** [comment]
You have `#/karma` in your URL, which effectively masks query filters.

A working link: https://demo.karma-dashboard.io/?q=%40cluster%3DHA&q=%40receiver%3Dby-cluster-service&q=alertname%3DDisk%20Free%20Low

**Comment by v0lk3r** [comment]
Thanks for the hint, manually editing the URL fixes my immediate problem. However the bad link is created by karma itself (updated in the browser location after applying the filter). The karma instance I am using is deployed  with the [latest helm chart](https://artifacthub.io/packages/helm/wiremind/karma) (version 1.8.0) and uses mostly default settings

**Comment by prymitive** [comment]
Please reproduce the issue on https://demo.karma-dashboard.io/  and provide steps or screenshot for that.

**Comment by v0lk3r** [comment]
I can't reproduce this on the demo installation, I am therefore closing this ticket. I'll try investigate if there's a bug in the helm chart (or the configuration)
