### ISSUE TITLE
Karma settings 'version' string customization

### ISSUE THREAD

**Issue by strus38** [prymitive/karma#3143]
Hi
Is it possible using the config file to customize the 'Version: DEV' string displayed in the 'settings' bottom of the panel?
I could not find this in a doc.
![karma-err1](https://user-images.githubusercontent.com/5890515/118945932-399f4f80-b956-11eb-88cc-dadd0f5a1b63.PNG)

Thanks

**Comment by prymitive** [comment]
Version string is calculated from git history on build, so sounds like you’re building out of a shallow clone or an archive with no git history. Resolving that would be the recommended solution if you need to build it yourself.
You can also run `make VERSION=Foo` if you feel the need to force a version string.
