### ISSUE TITLE
Case insensitive grouping and filtering

### ISSUE THREAD

**Issue by freeseacher** [prymitive/karma#3204]
Sometimes alerts have different case for alerts. 
Especially priopity field. someone setting it like p1 someone with P1
can you please add an option to make p1 and P1 the same while grouping and searching ?

**Comment by freeseacher** [comment]
not stale :(

**Comment by prymitive** [comment]
PromQL is case-sensitive so I see no reason why karma should have different behaviour.
I suggest to fix your alerts, https://github.com/cloudflare/pint can be used to ensure all labels have correct case.
