### ISSUE TITLE
Hide label name for selected labels?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3221]
Hello @prymitive !
I'd like to suggest a feature request, as part of the [feedback we got](https://phabricator.wikimedia.org/T284213) from SREs at Wikimedia Foundation. Namely to being able to display only the label's value and hide the label's name.

The feature we believe is most useful when the label's context is clear either from the color or the label value itself (`severity` in the case above, though `alertname` could apply too). What do you think?

Thank you!

**Comment by prymitive** [comment]
I did at some point entertain the idea of having name hidden until you hover over label, at least for things like `alertname`, but changing size of labels causes layout shifts in the browser, which is baaaad.
Adding a config option to always hide it for selected labels (with a tooltip that shows the whole key:val) is a good alternative.
Thanks

**Comment by prymitive** [comment]
Added in #3358

**Comment by filippog** [comment]
Thank you!
