### ISSUE TITLE
Remove grid labels from alert groups?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3222]
Hello @prymitive !
I'd like to suggest a feature request, as part of the [feedback we got](https://phabricator.wikimedia.org/T284213) from SREs at Wikimedia Foundation. Specifically being able to remove grid labels from the alert group boxes themselves, to save screen real estate and remove redundant information ('severity' in the task above for example is used for grid grouping) What do you think?

Thank you!

**Comment by prymitive** [comment]
I'll look into that, thanks

**Comment by prymitive** [comment]
Fixed via #3222

**Comment by filippog** [comment]
Thank you!
