### ISSUE TITLE
add /version api endpoint

### ISSUE THREAD

**Issue by sed-i** [prymitive/karma#3332]
Would be nice to be able to obtain the version of karma without parsing output of `exec` for `/karma --version`.
Alternatively, could incorporate /health and /version into /status.

**Comment by prymitive** [comment]
What would you need this for?

**Comment by sed-i** [comment]
Operator logic may vary depending on the version that runs in the container.
alertmanager has a similar [endpoint](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/prometheus/alertmanager/master/api/v2/openapi.yaml#/general/getStatus).

**Comment by prymitive** [comment]
Added `/version` endpoint via #3356
