### ISSUE TITLE
Filter by non-existent tags?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3353]
Hello @prymitive !
I'd like to suggest a feature request, as part of the [feedback we got](https://phabricator.wikimedia.org/T284213) from SREs at Wikimedia Foundation. Specifically being able to filter by a non-existent tag, i.e. "show me all alerts that don't have tag `x`". Is this possible already? Would it be a good feature for karma to have?

thank you!

**Comment by prymitive** [comment]
You can use a regex filter for that to filter out any alert with non-empty value (`!~.+`). For example to `show me all alerts that don't have tag device` you can pass:  `device!~.+`

**Comment by prymitive** [comment]
You can use a regex filter for that to filter out any alert with non-empty value `(!~.+)`. For example to `show me all alerts that don't have tag device you can pass`: `device!~.+`

**Comment by filippog** [comment]
That makes sense! See #3360 for an expansion of help modal with this example too, I think it'd be useful
