### ISSUE TITLE
Templating moustache is visible on empty Karma board

### ISSUE THREAD

**Issue by yurkeen** [prymitive/karma#3365]
Seems [ui/public/index.html ](https://github.com/prymitive/karma/blob/98edd7b07325f55d2f3631144eba31203f5bb32b/ui/public/index.html) is not being processed by templating engine anymore, so templating moustache is visible (inside rendered HTML too).
![image](https://user-images.githubusercontent.com/8747084/126636531-e8183211-f915-4014-9601-b14e83f3fcf6.png)

**Comment by prymitive** [comment]
You're probably running it in dev mode via `npm start`
npm doesn't know how to handle Go templates, it's not a bug

**Comment by yurkeen** [comment]
I tried different and seems it happens only when I run Karma as a PWA, while in browsers everything looks as it should. Sorry for the false alarm.
