### ISSUE TITLE
Internal error RangeError: value (5) is smaller than min (10)

### ISSUE THREAD

**Issue by sasah** [prymitive/karma#3368]
Internal error
RangeError: value (5) is smaller than min (10)

This page will auto refresh in 56s

**Comment by sasah** [comment]
+1

**Comment by prymitive** [comment]
Please provide some details on how to reproduce this.
Slider doesn't allow to set it to less than 5, did you manually modify local storage in your browser?

**Comment by sasah** [comment]
This error show in Chrome when i press Setting button in right upper corner.

**Comment by prymitive** [comment]
Clear website data for karma domain and it should work
