### ISSUE TITLE
Alert history not honoring generatorURL/source with path components

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3387]
Hello,
I'm running latest karma and noticed alert history can't be fetched when alerts contain a path prefix in their generatorurl/source:

* Prometheus is running with `--web.external-url http://prometheus.svc.eqiad.wmnet/ops`
* An alert comes in with e.g. `"generatorURL": "http://prometheus.svc.eqiad.wmnet/ops/graph?g0.expr=sum+by%28job%29+%28up%29+%2F+count+by%28job%29+%28up%29+%3C+0.95&g0.tab=1"`
* I see in the karma a 404 from the alert history bar
* Indeed karma issues the following to fetch alert history (without `/ops`) and gets a 404 `GET	prometheus.svc.eqiad.wmnet	/api/v1/labels?end=1627637466.5026662&match%5B%5D=%7B__name__%3D%22ALERTS_FOR_STATE%22%7D&start=1627637166.502666	HTTP/1.1`

**Comment by prymitive** [comment]
Path is getting nuked at the moment and that's why it doesn't work. Will need to extract everything up to `/graph?.+`

https://github.com/prymitive/karma/blob/main/internal/models/api.go#L268

**Comment by filippog** [comment]
Fantastic, thank you so much for the fix @prymitive !
