### ISSUE TITLE
duplicate/invalid matchers proposed for new silence over partially silenced group

### ISSUE THREAD

**Issue by jtougas** [prymitive/karma#3509]
When trying to silence a group that is already partially silenced (one alert is silenced, but another one isn't) results in duplicate/incorrect matchers.

A picture is worth a thousands words so:
![image](https://user-images.githubusercontent.com/7550618/132891322-2fbf4ed6-99b5-4e5a-95e4-a7711da18396.png)

This will result in matchers which won't match what is expected. `instance="123"` and `instance="789"` can't match anything. I believe the expected behavior would be to merge the matchers together to get `instance=~(123|789)`

This is running with karma:v0.90, alertmanager:v0.22.0

**Comment by prymitive** [comment]
Can reproduce on https://demo.karma-dashboard.io/?q=%40cluster%3DHA&q=%40receiver%3Dby-cluster-service&q=alertname%3DMixed%20Alerts

**Comment by prymitive** [comment]
Will be fixed via #3513, thanks!
