### ISSUE TITLE
Alert Popup and Noise

### ISSUE THREAD

**Issue by MstWntd** [prymitive/karma#3598]
Hi,

karma is an amazing project and really fills the gaps on the standard UI.

I have a feature request, I was hoping it might be possible to enhance the experience by adding popups and audible notifications for when new alerts arrive? Maybe making use of the [js notifcations api](https://developer.mozilla.org/en-US/docs/Web/API/notification)?

Thank you.

**Comment by xkilian** [comment]
Yeah, it seems that audio notification based on severity (label values of a given label) would be a desirable feature.
Audio notification could be different based on the label values. This is to use in the contact of control rooms where audio cues are a requirement.

**Comment by systembell** [comment]
Native browser notifications would be far more useful than audio alerts to me.
