### ISSUE TITLE
Use localtime in Acks

### ISSUE THREAD

**Issue by andreas-p** [prymitive/karma#3704]
Currently, an alertAcknowledgement.comment will use UTC time when the %NOW% macro is used. IMHO it's much more convenient if the local timezone is used.

**Comment by prymitive** [comment]
It's only convenient if all your teams are in one time zone, so I'd rather make it configurable than change to local time.

**Comment by prymitive** [comment]
Added `%NOWLOC%` that gets replaced with timestamp using local timezone via #3813
