### ISSUE TITLE
Wrong URL to the prometheus (Alert source links)

### ISSUE THREAD

**Issue by wolfedale** [prymitive/karma#3762]
I noticed that in the data/time section I have option to go right away to the Prometheus instance but instead of the proper Prometheus URL I see some random string.

<img width="614" alt="Screenshot 2021-12-02 at 17 12 32" src="https://user-images.githubusercontent.com/4375379/144459867-c6d8420b-8e5c-4ff2-a939-5748c69cf3d9.png">

Is it a but in Karma or I did something wrong? I cannot find any reference about it.

Thanks!

**Comment by wolfedale** [comment]
I think it's this part:

```
       <h6 className="dropdown-header">Alert source links:</h6>
        {alert.alertmanager.map((am) => (
          <MenuLink
            key={am.name}
            icon={faExternalLinkAlt}
            text={am.name}
            uri={am.source}
            afterClick={afterClick}
          />
        ))}
```

So looks like `am.source` is wrong. This data is coming from the alert-manager?

**Comment by prymitive** [comment]
It comes from alertmanager.
Sounds like you need to configure --web.external-url

See https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus

**Comment by wolfedale** [comment]
Thanks for the answer. I think that's not the issue. I see that I have `--web.external-url` specified in every single alert-manager deployment. I also noticed that for some alerts I see it correct and for most I see some random string. I have no idea what's the difference between them. I'm trying to figure it out.

**Comment by wolfedale** [comment]
I found the problem. Some of my alerts we from the other Prometheus instance (but by mistake they had wrong cluster-name and ID in the alert spec). This is why I was thinking alerts are coming from the proper Prometheus server. The other one had no `--web.external-url` like @prymitive said. Thanks! I'm closing it.
