### ISSUE TITLE
Feature Request : Collapse All + colorize severity

### ISSUE THREAD

**Issue by zenman94** [prymitive/karma#378]
Hi, thanks for the job, we like Unsee, and we appreciate Karma for reading gain.

We have two requests if that's possible, the first is the possibility of a "Collapse All" function to minimize the current view.
The seconds requests is the possibility to colorize the card according to the severity label (or other label). We need to differentiate quickly a warning or a critial alert.

We made some test with custom.js but I thnink we can't easily achieved this feature like this.

What do you think about this?

Regards

**Comment by prymitive** [comment]
Can you give me a bit more context on the "Collapse All"? How and when would you use that?
Side note: I did consider at some point adding an option to enable collapsing all groups by default, but didn't implement it due to limitations in the way lazy loading is currently handling.

When is comes to severity I'm guessing that you want to have something like "red for critical, yellow for warning ..." rather than random colors for each unique value (which is already there), right?

**Comment by zenman94** [comment]
We use Karma on top a big Prometheus / Thanos system with sometimes much alerts. We imagine to have a more readable alerting view with a "collapse all" function to reduce all block.

For the severity colization it's exactly that we expect, red for critical, yellow for warning...

**Comment by prymitive** [comment]
> We use Karma on top a big Prometheus / Thanos system with sometimes much alerts. We imagine to have a more readable alerting view with a "collapse all" function to reduce all block.

I could allow 0 value for `Default number of alerts to show per group` option in the settings modal, which would mean collapsed by default.
The problem AFAIR was that currently 50 groups get rendered initially (with the assumption that it's enough to fill the entire screen) and if there's more and user scrolls to the bottom more gets added. If the screen is not filled with the initial render then lazy loader didn't get triggered, effectively hiding all those extra groups. That's the only thing blocking adding that. I don't expect it a huge issue, I need to add a visibility checks so lazy loader knows for sure when to render extra groups, it's a bit of work, but was on my TODO for a long time, so I'll try to add it in the coming weeks. Right now as a work around you can set `Default number of alerts to show per group` to 1 and get almost what you want (be aware of potential lazy loader issues if you have a huge screen).

> For the severity colization it's exactly that we expect, red for critical, yellow for warning...

That is a fairly simple extension to the current value based color generator, needs a verbose configuration, but it's not much work, and I do agree that "human readable" colors are more useful for things like severity. I'll try to add it soon.

**Comment by prymitive** [comment]
#414 adds ability to set custom colors for specific labels:

```yaml
labels:
  color:
    custom:
      severity:
        info: "#87c4e0"
        warning: "#ffae42"
        critical: "#ff220c"
```

**Comment by zenman94** [comment]
Thanks for the work! It's exactly what we expect.

Futhermore, we achieve the "collapse all" function with custom js.

I close this issue.

**Comment by xkilian** [comment]
You achieved de collapse all by a custom.js function that you added to the karma page? The original feature request of collapsing all using a button on the karma page or a configuration item is still of interest to us as a means of making the alert view as clean as possible. I think I like more the idea of a collapse all button. As a configuration item could be problematic for those who prefer having it uncollapsed.. (User profiles).

Feature request: Add a collapse all button. After clicking the button, all alerts become collapsed. Any new alerts that would come in, would be uncollapsed(or become uncollapsed if it is a new alert within an existing group that was minimized) This could be a configuration option to keep everything collapsed even in new events but I think it would not be wise to run it as such..
