### ISSUE TITLE
[BUG] log format: json and timestamp: true disables json format

### ISSUE THREAD

**Issue by piotrrybicki** [prymitive/karma#3822]
Hello.

When I define log section in config like this:
```
log:
  config:    false
  level:     info
  format:    json
  requests:  false
  timestamp: false

```
it is working as expected and emitting logs in JSON format.
But when I change `timestamp: true` logs are emmited back in text format.

karma version: v0.94

Thanks

**Comment by prymitive** [comment]
Fix in #3832, thanks!
