### ISSUE TITLE
braces in silence matcher get interpreted in regex

### ISSUE THREAD

**Issue by jorisjean** [prymitive/karma#3866]
When trying to silence a group of alerts. If a label value has braces in it it gets interpreted as regex and does not match

![image](https://user-images.githubusercontent.com/20523713/148554572-dbb0fccc-3c5d-4b65-b78c-3cfb18b63fe2.png)
Special characters should be escaped by default when creating a group silence from the link
![image](https://user-images.githubusercontent.com/20523713/148554463-22b7b0a6-4d49-461b-a394-6ca77c31d4c6.png)

**Comment by prymitive** [comment]
Should be fixed via #3881
