### ISSUE TITLE
Duplicate silences will show "0" in impacted alerts

### ISSUE THREAD

**Issue by ngc104** [prymitive/karma#3909]
Karma-0.94

# How to reproduce :

In karma, set a silence on an alert.

Click on the top right clock "New Silence", then Browse and see your silence. You should see your silence with "1" as the number of alerts.

Set a new silence, exactly the same as before. There should now be 2 silences for that alert.

Click again on the top right clock "New Silence", then Browse and see your silence. You should now see the 2 silences.

Here is the bug : one silence shows "1" as the number of alerts. But the other one shows 0.

![image](https://user-images.githubusercontent.com/67380650/150775588-b48181eb-327b-4955-8c11-98580579be65.png)

# Investigations

## Alertmanager

In Alertmanager, we can see the 2 silences. Each silence show 1 affected alert. So the problem is probably not in Alertmanager.

Alertmanager version : 0.23.0

## Remove one silence

Remove one silence : remove the silence that showed "1" alert. Then refresh and check the other silence : the "0" is now "1".

# Expected behaviour

Click on the top right clock "New Silence", then Browse and see your silence.

For each silence we should see the number of affected alerts (just as in Alertmanager).

**Comment by prymitive** [comment]
Should be fixed in main branch, thanks
