### ISSUE TITLE
Regex - escaped characters not matching in alert manager

### ISSUE THREAD

**Issue by heapdavid** [prymitive/karma#3936]
Hi,

We upgraded to 0.95 this morning, and following on from https://github.com/prymitive/karma/pull/3881, we're now seeing silences not matching correctly when special chars are escaped in the regex.

Example - Top matcher is an expired alert, and bottom is a new remaking of it that's failing to match:

![image](https://user-images.githubusercontent.com/88432183/151953554-796f473e-b419-4fc4-a5b1-f8f49dec8038.png)

**Comment by erachenko23** [comment]
Have some problem with character escrape:

Alert:

![image](https://user-images.githubusercontent.com/43468129/151976262-ce1704d2-60f9-4a4a-a3f1-c41e3ff6fcb8.png)

Trying to create silence:

![image](https://user-images.githubusercontent.com/43468129/151976385-6a6137ed-5e4c-492e-b722-897f1af4dcdf.png)

Check alert in alertmanager:

![image](https://user-images.githubusercontent.com/43468129/151976577-bb699141-89c7-46a5-bf36-ebb96d2c3f06.png)

**Comment by smbambling** [comment]
Same issues as above, this unfortunately total breaks the usage of silences management for us as we have many labels with `-` or `.` in them that get escaped.

**Comment by xkilian** [comment]
Same here, reverting to 0.94.

**Comment by prymitive** [comment]
Should be fixed via #3945

**Comment by heapdavid** [comment]
Thanks, we've upgraded to v0.96 and given it a try.

While new silences seem to work well, recreating expired silences still seems to have the same problem.

**Comment by smbambling** [comment]
@heapdavid with this issue being closed this comment might be lost. If you still have .96 deployed would you mind creating another issue and linking this ? 

If not I'll try to deploy and instance and write up a new issue for tracking.

**Comment by prymitive** [comment]
#3947 should fix editing

**Comment by heapdavid** [comment]
@prymitive Thanks for sorting that out, we've had no problems with new or edited silences until today, a colleague uses the filtering in the top bar to create silences and that still seems to have the issue:

![image](https://user-images.githubusercontent.com/88432183/153171952-29273ea1-a51a-4b87-9022-3a1ae3e9a6fe.png)

![image](https://user-images.githubusercontent.com/88432183/153171969-e05965c5-c5df-4863-a075-f00a70572f90.png)

![image](https://user-images.githubusercontent.com/88432183/153171987-cd6adf01-7c51-49aa-8029-b9b5e1978929.png)

![image](https://user-images.githubusercontent.com/88432183/153172003-479d1e7e-4de4-4894-be22-850c9de1a570.png)

It also looks to be adding an extra `.*` either side of the regex that we're entering, but that may be a different issue.

**Comment by prymitive** [comment]
#3980 should fix that

**Comment by heapdavid** [comment]
Hi, thanks for all the work on this so far - I'm now seeing edited/recreated alerts failing again with v0.98:

![image](https://user-images.githubusercontent.com/88432183/154693692-286558c1-f9f8-43ba-b6c9-98dcc90bce5f.png)

**Comment by prymitive** [comment]
Raised another PR - #3997
