### ISSUE TITLE
Filter-on-click when instance has hostname:port

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#3938]
Hello,
thank you for your work on Karma! Truly useful. In our setup `instance` has the default/standard `host:port` form, therefore by clicking an `instance` label on the UI the filter added matches exactly host + port. In our case a more useful behavior would be to add a filter to match the host part only (i.e. show all alerts for the filtered host). Is there a recommendation / best practice for this case ? Thank you !

**Comment by prymitive** [comment]
I don't think it makes a lot of sense to apply value `B` when you click on `A`. It's a key/value pair, how would it even know to apply a different value?
I think the solution here is to normalise your labels, you're using 2 different values to identify the same entity and then face problem when trying to drill down on `instance`. Make it same value and the problem goes away.
