### ISSUE TITLE
HTTP 401 on creation / deletion silence after enabling base auth in proxy mode

### ISSUE THREAD

**Issue by erachenko23** [prymitive/karma#3942]
Karma 0.94
Alertmanager 0.23 (http. no auth)

Simple configration;

alertmanager:
  servers:
    - name: alertmananager
      uri: <secret_uri>
      proxy: true
      cors:
        credentials: omit

authentication:
  basicAuth:
    users:
      - username: test
        password: test

history:
  rewrite:
    - source: '(.*)'
      uri: <secret2_uri>
      tls:
        insecureSkipVerify: true

log:
  config: true
  level: debug
  format: text
  requests: true
  timestamp: true

receivers:
      keep: ["alert"]
      strip: ["alertmananger-bot"]

Run karma and test UI:

**1. Trying auth:** 

Browser show auth window on entry - OK.
![image](https://user-images.githubusercontent.com/43468129/152105460-c76074a3-6de3-4d0f-8686-63a86a58fa32.png)
After enter of login and password karma show main UI - OK
window with auth username and version:
![image](https://user-images.githubusercontent.com/43468129/152105685-15af90ea-9bea-47f4-bbd4-c302975aabf4.png)
overview:
![image](https://user-images.githubusercontent.com/43468129/152105738-cda16da2-616d-49bf-8613-79d02eb75936.png)

**2.  Create new silence**

Find active alert
![image](https://user-images.githubusercontent.com/43468129/152106240-fdbdb2c6-5c05-4136-862f-e175729d3d67.png)

Setup selince:
![image](https://user-images.githubusercontent.com/43468129/152106425-d479b779-7202-449e-af51-832c4b5a4c7a.png)

After submit, open alertmanager ui and check createtion of silince - NOK

karma        | 09:45:35 msg="Request completed" address=10.1.180.31:61573 bytes=0 code=401 duration="610.628µs" method=POST path=/proxy/alertmanager/alertmananager/api/v2/silences

in logs i see request with code 401 reply, but karma UI show green OK sign - NOK
![image](https://user-images.githubusercontent.com/43468129/152107091-2ab61add-391d-4244-8008-8dcd278f1452.png)

**3. Trying delete exist silence**

Find active suppressed
![image](https://user-images.githubusercontent.com/43468129/152107400-840d2d0a-c994-4301-b643-a8eeb3bc905c.png)
Setup deletetion and confirm
![image](https://user-images.githubusercontent.com/43468129/152107607-8e86d430-d8e9-41fd-8922-6b0c351999bf.png)
karma UI show green OK after confirm - NOK

check logs:

karma        | 09:54:26 msg="Request completed" address=10.1.180.31:50420 bytes=0 code=401 duration="336.457µs" method=DELETE path=/proxy/alertmanager/alertmananager/api/v2/silence/617b7e7b-e422-49c1-885f-7b4748ead1a3

check alertmanager ui for silence status
Slince  617b7e7b-e422-49c1-885f-7b4748ead1a3 still active - NOK
![image](https://user-images.githubusercontent.com/43468129/152108143-6dd5b7cc-994e-41a1-9413-b9e99b1445fe.png)

When i disable basic auth in karma, creation and deletetion working fine.

Quick test on Karma 0.95 - similar behavior

Maybe we have some configuration error? Thank you.

**Comment by prymitive** [comment]
Why do you have `credentials: omit` set?
I think your browser is stripping auth information from requests because of it. Try removing:

```
cors:
  credentials: omit
```

**Comment by erachenko23** [comment]
We set this parameter because in mode proxy: false (or parameter exists) on create silence wee seen this error.

![image](https://user-images.githubusercontent.com/43468129/152344367-b3b272af-388a-4f68-bb64-e82e46d58f57.png)

We make full retest cycle after applying recommendation: creating and deleteting silence with basic auth work fine. 

Thank a lot!! 

But i'm think then request end with 401 error karma ui must show error notification instead success. It's minor bug.
