### ISSUE TITLE
Feature Request: Card view disorienting

### ISSUE THREAD

**Issue by DagW** [prymitive/karma#424]
Hello! Really like your project.
Its hard to see and visually sort the alerts when there are more than a few.
A good'ol sortable table would work really well.
Any plans to implement a "table view"-mode?

**Comment by prymitive** [comment]
Sadly I don't have any plans for implementing any alternative view modes, my goal was to have a grid based dashboard and that's what the code is doing.
I hope to add some sorting ability in some undefined future if I have time to work on it, but that's pretty much it.

**Comment by DagW** [comment]
Ok thanks! Yes sorting would be nice. Just being able to put "debug" alerts below the "critical" ones would be a nice improvement.

**Comment by prymitive** [comment]
First round of sorting features will be added via #447, it doesn't fully solve all sorting needs since it's just alphabetical sort on selected labels, so you end up with `critical fatal info warning`.
Mapping label values to custom "weights" would be needed, I'll try working on that soonish.

**Comment by prymitive** [comment]
#454 should solve sorting for labels like `severity` where alphabetic sort doesn't really make sense

**Comment by prymitive** [comment]
#458 add ability to configure default sorting in the config file, so it doesn't require every user to open settings and click on the right options combo
