### ISSUE TITLE
Past alerts in karma

### ISSUE THREAD

**Issue by corporate-gadfly** [prymitive/karma#4422]
Since alertmanager doesn't persist state, is there any other way to see past alerts? A lot of times, I see alerts fly by and it would be nice to be able to see past alerts.

**Comment by prymitive** [comment]
Prometheus supports webhooks, all you need is some service that receives them and saves in a db of your choice.
https://github.com/cloudflare/alertmanager2es is an example of such service that uses ES for storage.
