### ISSUE TITLE
Feature request: table view

### ISSUE THREAD

**Issue by XioNoX** [prymitive/karma#4609]
Thanks for this tool!

We're relying more and more on Karma at the Wikimedia Foundation, mostly migrating from Icinga.
Despite trying all the possible UI settings I can't find a way to configure the Grid view in a way that display all the active alerts in an easy to grasp way (to me). From my usage, the nested elements negatively impact readability.

I think adding a simplified flat table view could significantly help. With customizable and sortable columns. Optional aggregation. 
Ideally show/hide the silenced alerts, but if I understand correctly that's another can of worms.

Please let me know what you think.

**Comment by smbambling** [comment]
@XioNoX Are you thinking something along the lines of the UI for Alerta ? https://alerta.io

**Comment by XioNoX** [comment]
I never tried Alerta (their demo websites are all down), but according to the screenshot I'd say something more lightweight than Alerta but indeed in the same spirit.
