### ISSUE TITLE
Problem when silencing alerts to alertmanager with name containing forward slash

### ISSUE THREAD

**Issue by boribas** [prymitive/karma#4674]
This is similar issues as described in [issue #3651](https://github.com/prymitive/karma/issues/3651), but occurs when using forward slash '/' within alertmanager name. 
Actually the fix [PR #3664](https://github.com/prymitive/karma/pull/3664) for [issue #3651](https://github.com/prymitive/karma/issues/3651) introduced **regression**.

**What happened?**
Creating silence fails with 404 "Not found" error.

**What to expect?**
Silence is properly set.

**What works?**
Problem doesn't exists in karma v0.92 and below.
Problem exists in karma v0.93 and above (up to current last version v0.108).
Problem can be also resolved by using for example spaces instead of forward slashes within alertmanager names.

**Comment by prymitive** [comment]
This seems to be due to https://github.com/go-chi/chi/issues/641

RawPath usage in chi means that a request for `/alertmanager/foo%2Fbar/` doesn't match alertmanager `foo/bar` since we'll have `Path: /alertmanager/foo/bar/` but `RawPath: /alertmanager/foo%2Fbar/`
