### ISSUE TITLE
UI - Ticket ID detection strips space before link in comment

### ISSUE THREAD

**Issue by heapdavid** [prymitive/karma#4706]
Hi,

Thanks for the advice last week on getting the rules working for ticket ID detection. We've got it working nicely now.

We've noticed that the space before the detected link is stripped out of the silence - only a little thing but looks odd:

![image](https://user-images.githubusercontent.com/88432183/191313827-e8d50f85-0232-4da5-ada0-fb96e04c2fbd.png)

becomes

![image](https://user-images.githubusercontent.com/88432183/191313762-8cc6eeea-fbe0-4364-957d-81fb9e558370.png)

**Comment by prymitive** [comment]
Thanks, should be fixed via #4713
