### ISSUE TITLE
export karma version as prometheus metric

### ISSUE THREAD

**Issue by oOHenry** [prymitive/karma#4764]
As many other prometheus tools it would be cool to export the karma version as metric. 
For example prometheus exports:
`prometheus_build_info{branch="HEAD", goversion="go1.18.5",revision="818d6e60888b2a3ea363aee8a9828c7bafd73699", version="2.38.0"}`
The build_info metric is helpful if you want to create a dashboard which visualizes all running versions of your prometheus components.

**Comment by prymitive** [comment]
Added `build_info` via #4771
