### ISSUE TITLE
Show button with GeneratorURL in alert.

### ISSUE THREAD

**Issue by n27051538** [prymitive/karma#4789]
Hello,
Is it possible to get button on alert with link to GeneratorURL?
[GeneratorURL](https://prometheus.io/docs/alerting/latest/notifications/#alert) is provided by AlertManager, so no need to add any additional labels.

**Comment by prymitive** [comment]
https://user-images.githubusercontent.com/114288/196164515-2d7809a8-0638-4af0-97d9-b709e461aa9b.mov

**Comment by n27051538** [comment]
WOW!
So simple. 
I used it for a few years and didn't realize that duration is such a useful button. Thank you.
