### ISSUE TITLE
authentication not passed to /silence

### ISSUE THREAD

**Issue by skyfrank** [prymitive/karma#484]
We authenticate using nginx auth_request.
When are using proxy mode in the configuration file.

When submitting a new silence, cookies are not sent with the POST, resulting in a 401.

Seems to be related to #24 ?

**Comment by prymitive** [comment]
I'm not familiar with `auth_request`, can you share more details, like which cookies are not sent with the silence POST? Thanks!

**Comment by skyfrank** [comment]
We use a cookie for authentication that is passed in a subrequest to our authentication server.

When the silence POST is made, no cookie is sent, even if the cookies are for the same domain and path.
But it works for /alerts.json, authentication cookie is sent and received in subrequest.

It seems that fetch does not send credential cookies by default, and that `{credentials: 'include'}` might be the needed there too ?

Thanks !

**Comment by prymitive** [comment]
Yes, that seems likely, fetch request for silences doesn't set it, raised #486 to add that

**Comment by prymitive** [comment]
I see that there's more places where it needs to be added, so I need to make more changes, deleting silences has the same issue most likely

**Comment by prymitive** [comment]
Raised #487 that adds it, it will be `alt+click`, holding `ctrl` when clicking opens a menu on mac, and alt seems like more logical choice anyway.

**Comment by prymitive** [comment]
PR merged and it's included in `karma:latest` docker image, if you pull now

**Comment by prymitive** [comment]
Did that solve your problem @skyfrank ?

**Comment by skyfrank** [comment]
> Did that solve your problem @skyfrank ?

I tested this morning with the release v0.27 and it indeed works ! 
Thank you very much !
