### ISSUE TITLE
Feature request: Mod+Click to add negative filter

### ISSUE THREAD

**Issue by bgagnon** [prymitive/karma#485]
I find myself clicking labels only to then edit the "key=value" entry to "key!=value".

A shortcut like Ctrl-Click would save a lot of time in filtering a busy dashboard!

**Comment by prymitive** [comment]
Yeah, I wanted to add a way of applying any filtering via a click, but wasn't sure how to implement the UI for it, one of the options was a popup that appears if you hover over a label.
A `ctr+click` seems like a good idea, I'll try adding that over weekend. Thanks!

**Comment by prymitive** [comment]
Raised #487 that adds it, it will be `alt+click`, holding `ctrl` when clicking opens a menu on mac, and alt seems like more logical choice anyway.

**Comment by bgagnon** [comment]
Awesome, thank you for implementing this!
