### ISSUE TITLE
Can't find the proper way to hide the "@receiver" label on alerts.

### ISSUE THREAD

**Issue by krptg0** [prymitive/karma#5043]
Hi, despite trying I can't find how to hide the @receiver label on alert card.
![image](https://user-images.githubusercontent.com/45569465/218784026-a16a479e-307d-4490-b530-09af29be7744.png)

I tried the logical solution for me which was to add it to : 

```
labels:
  strip:
    - "@receiver"
```

That doesn't seem to work. 

Thanks,

**Comment by prymitive** [comment]
You cannot hide it.
It is only visible if there are multiple receivers and it must be visible because otherwise you might have multiple identical alerts and no way of telling from where did it come from.
