### ISSUE TITLE
dispaly all alert histories including resolved status (relates to #4236 )

### ISSUE THREAD

**Issue by Matthiator** [prymitive/karma#5083]
My issue relates to: #4236 
Unfortunately the issue was closed without comment.
We have the same issue. Can anyone comment on this? Can the karma dashboard show all alert histories including resolved status?

**Comment by prymitive** [comment]
karma pulls all alerts from alertmanager, so all you see in karma is what's in alertmanager.
Alertmanager doesn't keep historical alerts AFAIK. To keep a history you need to use something that archives all alerts, like https://github.com/cloudflare/alertmanager2es.
