### ISSUE TITLE
Unable to copy value of annotation

### ISSUE THREAD

**Issue by sylr** [prymitive/karma#518]
When clicking on an annotation the value is hidden which makes it impossible to select and copy the value.

Could the hiding feature be binded to a double click or just activated when clicking on the key of the annotation ?

**Comment by prymitive** [comment]
I'll modify onClick actions so that you need to click the "minus" icon to hide, but to show you can still click anywhere. Raised #519 for that

**Comment by sylr** [comment]
Thanks!
