### ISSUE TITLE
Add an icon next to silence and gear for linking to Monitoring main page

### ISSUE THREAD

**Issue by xkilian** [prymitive/karma#588]
We all have a starting point for our monitoring systems: In our case it is a Grafana page that has a bunch of links to dashboard/documentation, some metrics, a live log of events, etc. 
When we arrive in Karma, there is no way to get back to our starting page. Having an icon and a link for going back to our monitoring start page would be very helpful. Also document where the image is located and that it can be replaced by a user provided image (so we can put our system related icon)
It is a minor enhancement, but I think it would greatly improve usability.
Keep up the good work!

**Comment by prymitive** [comment]
I'm not sure if I follow, do you mean a link to grafana main page (vs some specific dashboard)?
How does this link relate to the silence?

**Comment by xkilian** [comment]
It has no relation with silence or gear features. I simply referred to them positionally. I will whip up a little mockup to show what I mean.
This feature request is meant to provide a way,  unrelated to active alerts, to link back to one or more URLs (ex. a Grafana page, Prometheus/alerts, Alertmanager/#/silences)

**Comment by prymitive** [comment]
You can add links via alert annotations, is that not working for you?

**Comment by xkilian** [comment]
You are correct that you can add links in annotations. But these links should always provide context relative to  the firing alert(dashboard for the service in alert, documentation related to the alert, remediation procedure related to the alert). What I am talking about is a way to have general links back to useful pages from the Karma UI.
