### ISSUE TITLE
Metrics for healthchecks

### ISSUE THREAD

**Issue by jvandenbroek** [prymitive/karma#5895]
It would be nice to have metrics for healthchecks. I was thinking something like this:
```
karma_healthcheck_up{alertmanager="am", filter="prom1"} 1
karma_healthcheck_up{alertmanager="am", filter="prom2"} 1
```
Is this possible to implement this? Maybe with other metric naming and/or labels, this is just an example. Thank you!

**Comment by prymitive** [comment]
https://github.com/prymitive/karma/blob/25f920fc950eb7b56043d507a8c0fe9a5a191f8c/cmd/karma/metrics.go#L54

**Comment by prymitive** [comment]
There’s already a metric tracing status of last pull from alertmanager.

**Comment by jvandenbroek** [comment]
Thanks for you response. AFAIK these are 2 different metrics, alertmanager is for the state of the alertmanager instance itself, but healthchecks confirm the agents are reporting properly. I wouldn't mind if this specific alertmanager_up metric could be extended with filter label instead, however I think they serve different purposes. That's why I suggested an healthchecks metric instead. Otherwise I have to adapt (and keep using) the deadman switch daemon instead (which feels a bit redundant since karma already have this info).
