### ISSUE TITLE
[feature request] Replace prometeus host 

### ISSUE THREAD

**Issue by wirwolf** [prymitive/karma#5943]
Hi. 
I use this software for Kubernetes prom stack and when I open the dashboard page I see this log
```
level=error msg="History query failed" error="failed to query Prometheus for label names: Post \"http://rancher-monitoring-prometheus.cattle-monitoring-system:9090/api/v1/labels\": dial tcp: lookup rancher-monitoring-prometheus.cattle-monitoring-system on 127.0.0.11:53: no such host" labels={"alertname":"CPUThrottlingHigh","cluster":"***********","namespace":"cattle-monitoring-system","prometheus":"cattle-monitoring-system/rancher-monitoring-prometheus","severity":"info"} uri=http://rancher-monitoring-prometheus.cattle-monitoring-system:9090 worker=1
```
This problem is because Prometheus and the alert manager working in the internal Kubernetes network.
Please can you implement the feature to replace the base Prometheus host when application request additional information

**Comment by prymitive** [comment]
Please read the docs, it's already there:
https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md#alert-history

**Comment by prymitive** [comment]
History is the only place where karma talks to prometheus.
Labels on your alert are set by you, they come from your alerting rules and your prometheus/alertmanager config, karma is not the place to rewrite them.
