### ISSUE TITLE
Tooltips not rendering correctly in Chrome

### ISSUE THREAD

**Issue by willbuckner** [prymitive/karma#605]
Tooltip text when hovering over an alertname is not rendering correctly on Chrome 73/Mac. It's rendering as faint black text, as seen in the image below.

Karma v0.32

![Screen Shot 2019-04-09 at 2 11 21 PM](https://user-images.githubusercontent.com/1458615/55835853-c1f16c00-5ad1-11e9-9777-aad17c11a058.png)

**Comment by prymitive** [comment]
I can't reproduce this, maybe some assets didn't load properly for you? Can you verify that? Maybe try emptying cache in your browser?

**Comment by willbuckner** [comment]
This may have just been a cache issue; I can't reproduce anymore. Thanks!
