### ISSUE TITLE
Work with unmatched silences

### ISSUE THREAD

**Issue by mazhead** [prymitive/karma#625]
Not sure if I am not missing something or it is currently not possible.
I was following: https://github.com/prymitive/karma/issues/87
The creator of the issue had a point: where to view silences. 

To clarify, I mean silences which do NOT match any current alert. 

Use case: 
1. You create a silence in preparation of maintenance (match non-existing alerts, for example whole env=production)
2. During the maintenance, the silence matches alerts you wanted to silence (no issues here)
3. The maintenance lasted less then expected so you want to delete the silence, but currently no alerts are triggered -> can't do it via karma, have to go to alertmanager directly.

Please let me know if I am missing something obvious. 
And still want to thank you for your great work, really like the project.

**Comment by prymitive** [comment]
Karma doesn’t really have any standalone silence management capabilities. Mostly because it doesn’t really try to replace alertmanager, but rather focus on providing a dashboard for viewing and responding to alerts. So any features outside of that main scope are not really high on my todo list.

**Comment by mazhead** [comment]
Fair enough, was just wondering if I missed something. If it will ever come up in the feature list, I will be happy to test :)

**Comment by prymitive** [comment]
Just keep this ticket open, I’ll eventually get frustrated by the same thing and add it

**Comment by prymitive** [comment]
I'll try to do some work on it once I'll do the backend refactoring needed for Alertmanager >=0.16
Need to figure out the UI for it first

**Comment by prymitive** [comment]
Started working on this, it requires some biggish refactorings since current silence component is very much glued to the alert it's created against. Need to figure out the UI too, could make it a modal but then editing/deleting silences would open another modal.

**Comment by prymitive** [comment]
Added a basic UI via #1078

**Comment by elda45** [comment]
20191224-134339](https://user-images.githubusercontent.com/59011886/71451224-477f7f80-2726-11ea-846f-84ba6e52f555.png)
