### ISSUE TITLE
Support HTTP/SOCKS proxies for Alertmanager URLs

### ISSUE THREAD

**Issue by bgagnon** [prymitive/karma#633]
When using the `proxy: true` option, it would be useful to have the option to use an HTTP/SOCKS proxy. The use case is for an Alertmanager endpoint running in another network (or the Internet) only reachable through a corporate proxy.

**Comment by bgagnon** [comment]
If it would honor environment variables (`http_proxy`, `https_proxy` and `no_proxy`), that might be sufficient as well.

**Comment by bgagnon** [comment]
FWIW, Grafana has the same issue with proxied data sources -- grafana/grafana#15045

**Comment by prymitive** [comment]
Go `http.Client` should support `HTTP_PROXY` by default ([source](https://golang.org/pkg/net/http/#RoundTripper)), but that doesn't seem to work. Backend code for this is pretty messy and needs some love, but the good news is that alertmanager `>0.16` support will use openapi client, so hopefully that will make it work.
Not following `HTTP_PROXY` / `HTTPS_PROXY` while Go supports it seems like an obvious bug and I'll try to address this at some point, but as it requires a fair bit of refactoring and cleanups it won't be very soon, so don't hold your breath just yet. Thanks!

**Comment by prymitive** [comment]
Looks like this works now:

Started nc in listen mode on localhost:8081 to capture any request hitting it:
```
$ nc -v -l 127.0.0.1 8081
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Listening on 127.0.0.1:8081
```

Started karma with `http_proxy` env variable:
```
$ http_proxy="http://localhost:8081" ./karma --alertmanager.uri=http://www.example.com --log.config=false
INFO[0000] Using simple config with a single Alertmanager server 
INFO[0000] Version: v0.55-2-gaeff8d63                   
INFO[0000] [default] Configured Alertmanager source at http://www.example.com (proxied: false, readonly: false) 
INFO[0000] Initial Alertmanager query                   
INFO[0000] Pulling latest alerts and silences from Alertmanager 
INFO[0000] [default] Collecting alerts and silences     
INFO[0000] GET http://www.example.com/metrics timeout=40s 
```

And nc shows that it got the request:
```
$ nc -v -l 127.0.0.1 8081
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Listening on 127.0.0.1:8081
Ncat: Connection from 127.0.0.1.
Ncat: Connection from 127.0.0.1:39228.
GET http://www.example.com/metrics HTTP/1.1
Host: www.example.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
```

So looks like `http_proxy` env variable is handled correctly
