### ISSUE TITLE
Silences blocked by CORS.

### ISSUE THREAD

**Issue by maskota** [prymitive/karma#715]
Karma v0.36
Alertmanager v0.17
Both behind nginx proxy with their domains.
After submitting silence i get error:
Access to fetch at 'https://alertmanager..../api/v2/silences' from origin 'https://karma....' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

**Comment by prymitive** [comment]
That sounds like that's the `CORS` policy in the response from the nginx, can you change it to match the domain alertmanager is exposed under?
Or you could enable `proxy: true` in the alertmanager definition in [karma config](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#alertmanagers)

**Comment by maskota** [comment]
Thank you, proxy setting solved the problem.
