### ISSUE TITLE
Disable silence functionality

### ISSUE THREAD

**Issue by arnitolog** [prymitive/karma#754]
Hello,
is there any way to disable silence functionality?
We want to provide an ability to see a list of alerts to our Dev teams, but we don't want to allow them to create or delete any silences.
That is why I'm looking for a way to turn it off

**Comment by prymitive** [comment]
If the dev team can only connect to karma but not to alertmanager itself then you can just ensure that the proxy mode is disabled for every alertmanager instance configured in karma. Without proxy mode enabled karma only collects all alerts & silences from alertmanager but all silence requests go directly from user browser to alertmanager, so if they cannot connect they will get an error.
That's the most basic thing you can do out of the box

**Comment by arnitolog** [comment]
Thanks. that is exactly what I need!
