### ISSUE TITLE
Quick overview label

### ISSUE THREAD

**Issue by freeseacher** [prymitive/karma#766]
I imagine that it would be helpful to add new line with the same size like search bar and show label and count in it. 

Currently, except suppresed, i have 102 alerts. 
i want to get quick overview of alert count across team label. for example 
"team: `red: 23`, `blue: 15`, `white: 12`"
and so on.

**Comment by prymitive** [comment]
Something like that was on my TODO list, old unsee project had a popover that appeared when you hover over alert count and would show the list of top 10 (or so) labels with counters.
Not sure if that's the best UI but some sort of simple analytics is what I often miss when the grid gets full.

**Comment by prymitive** [comment]
Raised #802, preview should be ready on http://karma-demo.herokuapp.com in 30 minutes or so

**Comment by freeseacher** [comment]
> 30 minutes or so

but it is not, as far as i can see

**Comment by prymitive** [comment]
There was another pr that got deployed, it’s there now until a new pr is created

**Comment by prymitive** [comment]
here's a screenshot:

![screencapture-karma-demo-herokuapp-2019-07-04-09_44_29](https://user-images.githubusercontent.com/114288/60652663-910aa400-9e40-11e9-99c5-904a9629e5d0.png)

**Comment by prymitive** [comment]
I don't think that a filter bar is the best approach here, space limitation of a bar makes it hard to visually represent labels overview in a useful and informative way.
I think I'll add a modal that's triggered when you click on the alert counter, that will provide enough space for better visual representation and will allow to add more information there in the future without the need to struggle with limited space.

**Comment by freeseacher** [comment]
okay. can't wait to see any blueprints

**Comment by prymitive** [comment]
Version with overview modal
![screencapture-localhost-3000-2019-07-09-21_33_51](https://user-images.githubusercontent.com/114288/60920994-6af66100-a291-11e9-9fd3-9a8b64046049.png)

**Comment by prymitive** [comment]
Raised #814 with modal

**Comment by freeseacher** [comment]
as far as i can see current filter is empty. 
will it respect current filter ? if yes can i specify/prioritize labels that are meaningful for me ? 

my first idea was split current alert list into primary and secondary label. primary will help me identify whom and where and secondary "what"
for example i get alert toomuch5xx. labels like team and dc will help me identify whom and where and what can be used to drill down for it

**Comment by prymitive** [comment]
The modal shows an overview of all labels from same alerts as the ones currently rendered on the grid. It's a single data source, filters do apply.
I might add some configuration to control which labels are presented in the overview.
