### ISSUE TITLE
Not working at all on Firefox based signage system

### ISSUE THREAD

**Issue by fabianseitzbn** [prymitive/karma#77]
Moving from Unsee to Karma does not work on our signage system.

On one screen I get

> Internal error
> TypeError: Object.entries is not a function
> This page will auto refresh in xxx s

The number of seconds (xxx) is changing quickly - for every second that passes it is reduced by 4 seconds. There is a graphical exclamation mark in front of Internal.

On another screen I tried Karma and it just returns a blank turquoise screen without any elements.

The browser in our signage system is a Firefox "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0". Unfortunately I can't access any developer tools to give more information.

**Comment by prymitive** [comment]
`TypeError: Object.entries is not a function` seems like ff45 doesn't support es compatibility level react is being transpiled for, I'll take a look and try to force babel to generate more compatibile code if possible. Sounds like I should look into intergration tests with older browsers

**Comment by fabianseitzbn** [comment]
Thanks a lot! I suppose a lot of these signage systems rely on pretty outdated browsers. FF 45.0 is from 2016, so not that old but apparently too old in this case.

**Comment by prymitive** [comment]
It should be fairly easy, create-react-app uses https://babeljs.io/docs/en/babel-preset-env so we just need to adjust https://github.com/browserslist/browserslist config
Integration tests would also be handy to prove we generate code that works, but that's separate task

**Comment by prymitive** [comment]
JS code compatibility is one thing - I also need to consider bootstrap support for browsers and that seesm to be https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/
```
"browserslist": [
  "last 1 major version",
  ">= 1%",
  "Chrome >= 45",
  "Firefox >= 38",
  "Edge >= 12",
  "Explorer >= 10",
  "iOS >= 9",
  "Safari >= 9",
  "Android >= 4.4",
  "Opera >= 30"
]
```

So that's what I should really use

**Comment by prymitive** [comment]
It's going to be a bit more tricky - https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#supported-language-features 

```
Note that this project includes no polyfills by default.

If you use any other ES6+ features that need runtime support (such as Array.from() or Symbol), make sure you are including the appropriate polyfills manually, or that the browsers you are targeting already support them.
```

I need to add polyfills for some features

**Comment by prymitive** [comment]
@fabianseitzbn I have #81 open that should fix this (tested with FF 44), but looks like create-react-app 2.0 is just a few days away and that would allow for a bit nicer solution to this, give it a few days and it should be resolved, thanks

**Comment by fabianseitzbn** [comment]
Thanks for putting so much effort into this. There is no hurry for me - we were pretty happy with Unsee, but moving forward would be nice :-)

**Comment by prymitive** [comment]
- [ ] Add browserslist config to package.json, mirroring bootstrap4 would make sense
- [ ] Add https://github.com/amilajack/eslint-plugin-compat so eslint checks
- [ ] Add polyfills, it should be a smaller bundle with react-create-app v2

**Comment by prymitive** [comment]
Added polyfills and http://karma-demo.herokuapp.com now works under FF 44

**Comment by fabianseitzbn** [comment]
I have deployed the latest version and it seems to be working fine now. Thanks a lot!
