### ISSUE TITLE
Connection refused on localhost

### ISSUE THREAD

**Issue by ben-r** [prymitive/karma#840]
I'm running alertmanager with `docker run -p 9093:9093  prom/alertmanager`
and karma with `docker run -p 8080:8080 -e ALERTMANAGER_URI=http://localhost:9093 lmierzwa/karma:latest`

I'm getting following error message:
```
time="2019-07-23T14:58:31Z" level=info msg="GET http://localhost:9093/metrics timeout=40s"
time="2019-07-23T14:58:31Z" level=error msg="[default] http://localhost:9093/metrics request failed: Get http://localhost:9093/metrics: dial tcp 127.0.0.1:9093: connect: connection refused"
time="2019-07-23T14:58:31Z" level=error msg="[default] Get http://localhost:9093/api/v2/status: dial tcp 127.0.0.1:9093: connect: connection refused"
```

while the mentioned URI's work perfectly fine in my browser & via CURL.

**Comment by prymitive** [comment]
I don't think this will work, I think that each container gets a dedicated loopback inside and so `localhost` inside a container points only to that container, it's not accessible from outside. The only way to workaround it would be to use host networking. But I might be mistaken here, best to check with your local docker user group. Unless I'm missing something this isn't really an issue with karma but rather with docker networking.

**Comment by ben-r** [comment]
Yes, sounds reasonable. I'll close this then

**Comment by ben-r** [comment]
Got it working with docker compose.
On docker Mac you can also just use this `docker run -p 8080:8080 -e ALERTMANAGER_URI=http://host.docker.internal:9093 lmierzwa/karma:latest`
