### ISSUE TITLE
Dismiss modal dialogs upon pressing ESC

### ISSUE THREAD

**Issue by bgagnon** [prymitive/karma#842]
This is a minor feature request to have the ability to dismiss the various modal dialogs with a simple press on the ESC key. This is just a first step in a larger desire for general keyboard navigation in the UI.

**Comment by prymitive** [comment]
The main reason keyboard shortcuts are missing is that I don't use them very often.
I'm happy to add more, but I suspect there might be some conflicts with the focus stealing filter input.

**Comment by prymitive** [comment]
Raised #848 that adds support for this - all modals are closed when you hit Escape unless you're focused on some input
