### ISSUE TITLE
Feature request: view and edit silences in Karma

### ISSUE THREAD

**Issue by dannyk81** [prymitive/karma#87]
Creating silences in Karma is super nice! we use it all the time, especially that we can define the same silence on multiple alert managers (in our case in different datacenters).

It would be great if we could also view and edit silences, as we need to jump to the AM UI for that now.

WDYT? @prymitive

**Comment by prymitive** [comment]
Extending expiring silences was on my TODO, editing the entire silence seems like a good idea too, so maybe I should implement that instead (or both).
When you say "view silences" what do you mean exactly? Is that different from what the current UI offers? Or maybe it's not obvious enough that you can click the expand button on each silence to show details? Thanks

**Comment by dannyk81** [comment]
@prymitive thanks for the reply! actually, feeling kind of dumb about the "view" part, indeed we can see any configured/silenced alerts.

It's actually quite intuitive (the view part), only thing I could maybe suggest is use `@silenced` instead of `@suppressed`? but that's just being picky.

So I guess just the editing part 😄 🙏

**Comment by prymitive** [comment]
Alert states are defined by Alertmanager, see [here](https://github.com/prometheus/alertmanager/blob/dac673a6aa183a2a0787e63e8cfa1701965975b6/types/types.go#L27-L29). And there's a reason Alertmanager uses "suppressed" rather than "silenced" - there's more than 1 way to prevent alert from generating notifications:
* create a silence that matches it
* setup inhibition rules that cause some alerts to suppress other alerts
And I think with that flow "suppressed" is a more generic state description, hence makes more sense.

**Comment by dannyk81** [comment]
Ahh, understood! in that case it makes sense indeed.

thanks for the clarification.

**Comment by prymitive** [comment]
Updating silences with the current API means adding `id` to the POST body:
```
fetch("http://localhost:9093/api/v1/silences", {
  "credentials":"include",
  "body":"{
    \"id\":\"8a7de6d9-c164-4ea8-b09f-57f0829df513\",
    \"createdBy\":\"foo@bar\",
    \"comment\":\"xxx\",
    \"startsAt\":\"2018-09-29T20:12:07.616Z\",
    \"endsAt\":\"2018-09-29T22:11:47.229Z\",
    \"matchers\":[
      {\"name\":\"foo\",\"value\":\"bar\",\"isRegex\":false},
      {\"name\":\"baz\",\"value\":\"baz\",\"isRegex\":false}
    ]
  }",
  "method":"POST"
});
```
So editing a silence that needs to be updated in a single Alertmanager is easy, but would be nice to be able to mass-manage silences. For that I will also need to (finally) deduplicate silences properly, right now they are not which means more memory usage if same silence is created on multiple alertmanager instances.
I'll start with adding edit support for a single silence, but I'll need to refactor a few things around it (which is already on my TODO).

**Comment by prymitive** [comment]
Merged support for editing silences, if you go to [the demo page](http://karma-demo.herokuapp.com/?q=%40receiver%3Dby-cluster-service&q=%40state%3Dsuppressed) and expand any silence there will be now edit button

<img width="535" alt="screen shot 2018-10-01 at 22 04 37" src="https://user-images.githubusercontent.com/114288/46315721-13221f80-c5c6-11e8-92f8-218d1b69ff4e.png">

**Comment by dannyk81** [comment]
cool stuff @prymitive 😄
