### ISSUE TITLE
Match os/architectures to be the same as alertmanager?

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#891]
Hi,
for folks running karma on the same hosts as alertmanager (and/or prometheus) I think it'll be nice to match karma's os+arch combinations to be the same as alertmanager, what do you think?

In practice I think the combinations missing are these ATM

```
freebsd-armv6
freebsd-armv7
linux-arm64
linux-armv5
linux-armv6
linux-armv7
linux-s390x
netbsd-armv6
netbsd-armv7
```

**Comment by prymitive** [comment]
I need to see why those are not getting build, maybe I should switch to promu for cross builds

**Comment by prymitive** [comment]
Next release will have all binaries - https://travis-ci.com/prymitive/karma/jobs/228925200#L316-L392
