### ISSUE TITLE
Alertmanager "external uri" for frontend code to use in non-proxied mode

### ISSUE THREAD

**Issue by filippog** [prymitive/karma#899]
I'm in a situation where karma is running in non-proxied mode and has read-only access to AM's API via an internal uri (e.g. `localhost`). The user's browser has read/write access to AM's API via an external uri e.g `alerts.domain.foo`. Thus to be able to add silences via the external uri, karma would need to know what AM's external uri is and generate the correct API requests. I couldn't find such flag/config (e.g. `--alertmanager.uri.external`) hence this feature request, thanks!

**Comment by prymitive** [comment]
added `external_uri` option via #900, please check if that works as you expect

**Comment by filippog** [comment]
Can confirm it works as expected, thanks a lot! :+1:
