### ISSUE TITLE
leaking basic auth creds in the UI

### ISSUE THREAD

**Issue by cuotos** [prymitive/karma#971]
When a post to silence an alert fails, it prints the basic auth creds in the UI. 

The popup error window contains:

broken
Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: http://TheUsername:ThePassword@AlertmanagerUrl

Can the creds be obfuscated of being printed to the ui?

**Comment by prymitive** [comment]
Errors when proxy mode is enabled should be obfuscated by Go itself, but same needs to be done for those that go directly.

**Comment by prymitive** [comment]
Another issue is that setting username & password in the URL won't work with `fetch()`, one needs to setup `Authorization` headers for that - https://stackoverflow.com/questions/45067331/request-with-url-that-includes-credentials

**Comment by prymitive** [comment]
This should be fixed via #974
