### ISSUE TITLE
Missing travis image and build

### ISSUE THREAD

**Issue by nledez** [prymitive/karma#996]
Hi,

I add Travis image build status in https://github.com/prymitive/karma/pull/995

And I think you forgot to activate Travis on that repository.

Thanks.

**Comment by prymitive** [comment]
travis is active - https://travis-ci.com/prymitive/karma
I've disabled PR builds to avoid double CI jobs, but didn't realise it blocks CI runs on PRs started from forks, need to fix that

**Comment by nledez** [comment]
Ho! I search on travis-ci.org!

**Comment by prymitive** [comment]
PRs got re-enabled, so future PRs should work

**Comment by nledez** [comment]
Thanks!
